package com.generator.mapper;

import com.generator.pojo.CountyInformation;
import com.generator.pojo.CountyInformationExample;
import com.generator.pojo.CountyInformationKey;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface CountyInformationMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table county_information
     *
     * @mbggenerated
     */
    int countByExample(CountyInformationExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table county_information
     *
     * @mbggenerated
     */
    int deleteByExample(CountyInformationExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table county_information
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(CountyInformationKey key);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table county_information
     *
     * @mbggenerated
     */
    int insert(CountyInformation record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table county_information
     *
     * @mbggenerated
     */
    int insertSelective(CountyInformation record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table county_information
     *
     * @mbggenerated
     */
    List<CountyInformation> selectByExample(CountyInformationExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table county_information
     *
     * @mbggenerated
     */
    CountyInformation selectByPrimaryKey(CountyInformationKey key);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table county_information
     *
     * @mbggenerated
     */
    int updateByExampleSelective(@Param("record") CountyInformation record, @Param("example") CountyInformationExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table county_information
     *
     * @mbggenerated
     */
    int updateByExample(@Param("record") CountyInformation record, @Param("example") CountyInformationExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table county_information
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(CountyInformation record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table county_information
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(CountyInformation record);
}