package com.generator.mapper;

import com.generator.pojo.DataInstruction;
import com.generator.pojo.DataInstructionExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface DataInstructionMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table data_instruction
     *
     * @mbggenerated
     */
    int countByExample(DataInstructionExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table data_instruction
     *
     * @mbggenerated
     */
    int deleteByExample(DataInstructionExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table data_instruction
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(String idelement);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table data_instruction
     *
     * @mbggenerated
     */
    int insert(DataInstruction record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table data_instruction
     *
     * @mbggenerated
     */
    int insertSelective(DataInstruction record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table data_instruction
     *
     * @mbggenerated
     */
    List<DataInstruction> selectByExample(DataInstructionExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table data_instruction
     *
     * @mbggenerated
     */
    DataInstruction selectByPrimaryKey(String idelement);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table data_instruction
     *
     * @mbggenerated
     */
    int updateByExampleSelective(@Param("record") DataInstruction record, @Param("example") DataInstructionExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table data_instruction
     *
     * @mbggenerated
     */
    int updateByExample(@Param("record") DataInstruction record, @Param("example") DataInstructionExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table data_instruction
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(DataInstruction record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table data_instruction
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(DataInstruction record);
}