package com.generator.mapper;

import com.generator.pojo.StationInstruction;
import com.generator.pojo.StationInstructionExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface StationInstructionMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table station_instruction
     *
     * @mbggenerated
     */
    int countByExample(StationInstructionExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table station_instruction
     *
     * @mbggenerated
     */
    int deleteByExample(StationInstructionExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table station_instruction
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Integer numdistricystation);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table station_instruction
     *
     * @mbggenerated
     */
    int insert(StationInstruction record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table station_instruction
     *
     * @mbggenerated
     */
    int insertSelective(StationInstruction record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table station_instruction
     *
     * @mbggenerated
     */
    List<StationInstruction> selectByExample(StationInstructionExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table station_instruction
     *
     * @mbggenerated
     */
    StationInstruction selectByPrimaryKey(Integer numdistricystation);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table station_instruction
     *
     * @mbggenerated
     */
    int updateByExampleSelective(@Param("record") StationInstruction record, @Param("example") StationInstructionExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table station_instruction
     *
     * @mbggenerated
     */
    int updateByExample(@Param("record") StationInstruction record, @Param("example") StationInstructionExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table station_instruction
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(StationInstruction record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table station_instruction
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(StationInstruction record);
}