package com.zxh.ssm.module.user.mapper;

import com.zxh.ssm.module.user.pojo.CaseRevisedInformation;
import com.zxh.ssm.module.user.pojo.CaseRevisedInformationExample;
import com.zxh.ssm.module.user.pojo.CaseRevisedInformationKey;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface CaseRevisedInformationMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table case_revised_information
     *
     * @mbggenerated
     */
    int countByExample(CaseRevisedInformationExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table case_revised_information
     *
     * @mbggenerated
     */
    int deleteByExample(CaseRevisedInformationExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table case_revised_information
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(CaseRevisedInformationKey key);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table case_revised_information
     *
     * @mbggenerated
     */
    int insert(CaseRevisedInformation record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table case_revised_information
     *
     * @mbggenerated
     */
    int insertSelective(CaseRevisedInformation record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table case_revised_information
     *
     * @mbggenerated
     */
    List<CaseRevisedInformation> selectByExample(CaseRevisedInformationExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table case_revised_information
     *
     * @mbggenerated
     */
    CaseRevisedInformation selectByPrimaryKey(CaseRevisedInformationKey key);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table case_revised_information
     *
     * @mbggenerated
     */
    int updateByExampleSelective(@Param("record") CaseRevisedInformation record, @Param("example") CaseRevisedInformationExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table case_revised_information
     *
     * @mbggenerated
     */
    int updateByExample(@Param("record") CaseRevisedInformation record, @Param("example") CaseRevisedInformationExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table case_revised_information
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(CaseRevisedInformation record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table case_revised_information
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(CaseRevisedInformation record);
}