package com.zxh.ssm.module.user.mapper;

import com.zxh.ssm.module.user.pojo.PatientCasesInformation;
import com.zxh.ssm.module.user.pojo.PatientCasesInformationExample;
import com.zxh.ssm.module.user.pojo.PatientCasesInformationKey;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface PatientCasesInformationMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table patient_cases_information
     *
     * @mbggenerated
     */
    int countByExample(PatientCasesInformationExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table patient_cases_information
     *
     * @mbggenerated
     */
    int deleteByExample(PatientCasesInformationExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table patient_cases_information
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(PatientCasesInformationKey key);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table patient_cases_information
     *
     * @mbggenerated
     */
    int insert(PatientCasesInformation record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table patient_cases_information
     *
     * @mbggenerated
     */
    int insertSelective(PatientCasesInformation record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table patient_cases_information
     *
     * @mbggenerated
     */
    List<PatientCasesInformation> selectByExample(PatientCasesInformationExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table patient_cases_information
     *
     * @mbggenerated
     */
    PatientCasesInformation selectByPrimaryKey(PatientCasesInformationKey key);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table patient_cases_information
     *
     * @mbggenerated
     */
    int updateByExampleSelective(@Param("record") PatientCasesInformation record, @Param("example") PatientCasesInformationExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table patient_cases_information
     *
     * @mbggenerated
     */
    int updateByExample(@Param("record") PatientCasesInformation record, @Param("example") PatientCasesInformationExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table patient_cases_information
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(PatientCasesInformation record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table patient_cases_information
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(PatientCasesInformation record);
}