package com.zxh.ssm.module.user.pojo;

public class CardInformationKey {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column card_information.year
     *
     * @mbggenerated
     */
    private Integer year;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column card_information.cardID
     *
     * @mbggenerated
     */
    private Integer cardid;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column card_information.year
     *
     * @return the value of card_information.year
     *
     * @mbggenerated
     */
    public Integer getYear() {
        return year;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column card_information.year
     *
     * @param year the value for card_information.year
     *
     * @mbggenerated
     */
    public void setYear(Integer year) {
        this.year = year;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column card_information.cardID
     *
     * @return the value of card_information.cardID
     *
     * @mbggenerated
     */
    public Integer getCardid() {
        return cardid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column card_information.cardID
     *
     * @param cardid the value for card_information.cardID
     *
     * @mbggenerated
     */
    public void setCardid(Integer cardid) {
        this.cardid = cardid;
    }
}