package com.zxh.ssm.module.user.pojo;

public class CaseRevisedInformation extends CaseRevisedInformationKey {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column case_revised_information.diseasePreRevised
     *
     * @mbggenerated
     */
    private String diseaseprerevised;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column case_revised_information.revisedReportDate
     *
     * @mbggenerated
     */
    private String revisedreportdate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column case_revised_information.revisedFinalJudgDate
     *
     * @mbggenerated
     */
    private String revisedfinaljudgdate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column case_revised_information.finalJudgDeathDate
     *
     * @mbggenerated
     */
    private String finaljudgdeathdate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column case_revised_information.reviseUser
     *
     * @mbggenerated
     */
    private String reviseuser;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column case_revised_information.reviseUserUnit
     *
     * @mbggenerated
     */
    private String reviseuserunit;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column case_revised_information.delDate
     *
     * @mbggenerated
     */
    private String deldate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column case_revised_information.delUser
     *
     * @mbggenerated
     */
    private String deluser;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column case_revised_information.delUserUnit
     *
     * @mbggenerated
     */
    private String deluserunit;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column case_revised_information.delReason
     *
     * @mbggenerated
     */
    private String delreason;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column case_revised_information.diseasePreRevised
     *
     * @return the value of case_revised_information.diseasePreRevised
     *
     * @mbggenerated
     */
    public String getDiseaseprerevised() {
        return diseaseprerevised;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column case_revised_information.diseasePreRevised
     *
     * @param diseaseprerevised the value for case_revised_information.diseasePreRevised
     *
     * @mbggenerated
     */
    public void setDiseaseprerevised(String diseaseprerevised) {
        this.diseaseprerevised = diseaseprerevised == null ? null : diseaseprerevised.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column case_revised_information.revisedReportDate
     *
     * @return the value of case_revised_information.revisedReportDate
     *
     * @mbggenerated
     */
    public String getRevisedreportdate() {
        return revisedreportdate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column case_revised_information.revisedReportDate
     *
     * @param revisedreportdate the value for case_revised_information.revisedReportDate
     *
     * @mbggenerated
     */
    public void setRevisedreportdate(String revisedreportdate) {
        this.revisedreportdate = revisedreportdate == null ? null : revisedreportdate.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column case_revised_information.revisedFinalJudgDate
     *
     * @return the value of case_revised_information.revisedFinalJudgDate
     *
     * @mbggenerated
     */
    public String getRevisedfinaljudgdate() {
        return revisedfinaljudgdate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column case_revised_information.revisedFinalJudgDate
     *
     * @param revisedfinaljudgdate the value for case_revised_information.revisedFinalJudgDate
     *
     * @mbggenerated
     */
    public void setRevisedfinaljudgdate(String revisedfinaljudgdate) {
        this.revisedfinaljudgdate = revisedfinaljudgdate == null ? null : revisedfinaljudgdate.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column case_revised_information.finalJudgDeathDate
     *
     * @return the value of case_revised_information.finalJudgDeathDate
     *
     * @mbggenerated
     */
    public String getFinaljudgdeathdate() {
        return finaljudgdeathdate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column case_revised_information.finalJudgDeathDate
     *
     * @param finaljudgdeathdate the value for case_revised_information.finalJudgDeathDate
     *
     * @mbggenerated
     */
    public void setFinaljudgdeathdate(String finaljudgdeathdate) {
        this.finaljudgdeathdate = finaljudgdeathdate == null ? null : finaljudgdeathdate.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column case_revised_information.reviseUser
     *
     * @return the value of case_revised_information.reviseUser
     *
     * @mbggenerated
     */
    public String getReviseuser() {
        return reviseuser;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column case_revised_information.reviseUser
     *
     * @param reviseuser the value for case_revised_information.reviseUser
     *
     * @mbggenerated
     */
    public void setReviseuser(String reviseuser) {
        this.reviseuser = reviseuser == null ? null : reviseuser.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column case_revised_information.reviseUserUnit
     *
     * @return the value of case_revised_information.reviseUserUnit
     *
     * @mbggenerated
     */
    public String getReviseuserunit() {
        return reviseuserunit;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column case_revised_information.reviseUserUnit
     *
     * @param reviseuserunit the value for case_revised_information.reviseUserUnit
     *
     * @mbggenerated
     */
    public void setReviseuserunit(String reviseuserunit) {
        this.reviseuserunit = reviseuserunit == null ? null : reviseuserunit.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column case_revised_information.delDate
     *
     * @return the value of case_revised_information.delDate
     *
     * @mbggenerated
     */
    public String getDeldate() {
        return deldate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column case_revised_information.delDate
     *
     * @param deldate the value for case_revised_information.delDate
     *
     * @mbggenerated
     */
    public void setDeldate(String deldate) {
        this.deldate = deldate == null ? null : deldate.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column case_revised_information.delUser
     *
     * @return the value of case_revised_information.delUser
     *
     * @mbggenerated
     */
    public String getDeluser() {
        return deluser;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column case_revised_information.delUser
     *
     * @param deluser the value for case_revised_information.delUser
     *
     * @mbggenerated
     */
    public void setDeluser(String deluser) {
        this.deluser = deluser == null ? null : deluser.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column case_revised_information.delUserUnit
     *
     * @return the value of case_revised_information.delUserUnit
     *
     * @mbggenerated
     */
    public String getDeluserunit() {
        return deluserunit;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column case_revised_information.delUserUnit
     *
     * @param deluserunit the value for case_revised_information.delUserUnit
     *
     * @mbggenerated
     */
    public void setDeluserunit(String deluserunit) {
        this.deluserunit = deluserunit == null ? null : deluserunit.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column case_revised_information.delReason
     *
     * @return the value of case_revised_information.delReason
     *
     * @mbggenerated
     */
    public String getDelreason() {
        return delreason;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column case_revised_information.delReason
     *
     * @param delreason the value for case_revised_information.delReason
     *
     * @mbggenerated
     */
    public void setDelreason(String delreason) {
        this.delreason = delreason == null ? null : delreason.trim();
    }
}