package com.zxh.ssm.module.user.pojo;

public class CaseReportInformation extends CaseReportInformationKey {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column case_report_information.reportUnitAreaCode
     *
     * @mbggenerated
     */
    private Integer reportunitareacode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column case_report_information.reportUnit
     *
     * @mbggenerated
     */
    private String reportunit;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column case_report_information.unitType
     *
     * @mbggenerated
     */
    private String unittype;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column case_report_information.reportInputDate
     *
     * @mbggenerated
     */
    private String reportinputdate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column case_report_information.inputUser
     *
     * @mbggenerated
     */
    private String inputuser;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column case_report_information.inputUserUnit
     *
     * @mbggenerated
     */
    private String inputuserunit;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column case_report_information.reportUnitAreaCode
     *
     * @return the value of case_report_information.reportUnitAreaCode
     *
     * @mbggenerated
     */
    public Integer getReportunitareacode() {
        return reportunitareacode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column case_report_information.reportUnitAreaCode
     *
     * @param reportunitareacode the value for case_report_information.reportUnitAreaCode
     *
     * @mbggenerated
     */
    public void setReportunitareacode(Integer reportunitareacode) {
        this.reportunitareacode = reportunitareacode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column case_report_information.reportUnit
     *
     * @return the value of case_report_information.reportUnit
     *
     * @mbggenerated
     */
    public String getReportunit() {
        return reportunit;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column case_report_information.reportUnit
     *
     * @param reportunit the value for case_report_information.reportUnit
     *
     * @mbggenerated
     */
    public void setReportunit(String reportunit) {
        this.reportunit = reportunit == null ? null : reportunit.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column case_report_information.unitType
     *
     * @return the value of case_report_information.unitType
     *
     * @mbggenerated
     */
    public String getUnittype() {
        return unittype;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column case_report_information.unitType
     *
     * @param unittype the value for case_report_information.unitType
     *
     * @mbggenerated
     */
    public void setUnittype(String unittype) {
        this.unittype = unittype == null ? null : unittype.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column case_report_information.reportInputDate
     *
     * @return the value of case_report_information.reportInputDate
     *
     * @mbggenerated
     */
    public String getReportinputdate() {
        return reportinputdate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column case_report_information.reportInputDate
     *
     * @param reportinputdate the value for case_report_information.reportInputDate
     *
     * @mbggenerated
     */
    public void setReportinputdate(String reportinputdate) {
        this.reportinputdate = reportinputdate == null ? null : reportinputdate.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column case_report_information.inputUser
     *
     * @return the value of case_report_information.inputUser
     *
     * @mbggenerated
     */
    public String getInputuser() {
        return inputuser;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column case_report_information.inputUser
     *
     * @param inputuser the value for case_report_information.inputUser
     *
     * @mbggenerated
     */
    public void setInputuser(String inputuser) {
        this.inputuser = inputuser == null ? null : inputuser.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column case_report_information.inputUserUnit
     *
     * @return the value of case_report_information.inputUserUnit
     *
     * @mbggenerated
     */
    public String getInputuserunit() {
        return inputuserunit;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column case_report_information.inputUserUnit
     *
     * @param inputuserunit the value for case_report_information.inputUserUnit
     *
     * @mbggenerated
     */
    public void setInputuserunit(String inputuserunit) {
        this.inputuserunit = inputuserunit == null ? null : inputuserunit.trim();
    }
}