package com.zxh.ssm.module.user.pojo;

public class IndicatorKey {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column indicator.fieldName
     *
     * @mbggenerated
     */
    private String fieldname;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column indicator.belongTable
     *
     * @mbggenerated
     */
    private String belongtable;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column indicator.fieldName
     *
     * @return the value of indicator.fieldName
     *
     * @mbggenerated
     */
    public String getFieldname() {
        return fieldname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column indicator.fieldName
     *
     * @param fieldname the value for indicator.fieldName
     *
     * @mbggenerated
     */
    public void setFieldname(String fieldname) {
        this.fieldname = fieldname == null ? null : fieldname.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column indicator.belongTable
     *
     * @return the value of indicator.belongTable
     *
     * @mbggenerated
     */
    public String getBelongtable() {
        return belongtable;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column indicator.belongTable
     *
     * @param belongtable the value for indicator.belongTable
     *
     * @mbggenerated
     */
    public void setBelongtable(String belongtable) {
        this.belongtable = belongtable == null ? null : belongtable.trim();
    }
}