package com.zxh.ssm.module.whole.mapper;

import com.zxh.ssm.module.whole.pojo.CaseJudgmentInformation;
import com.zxh.ssm.module.whole.pojo.CaseJudgmentInformationExample;
import com.zxh.ssm.module.whole.pojo.CaseJudgmentInformationKey;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface CaseJudgmentInformationMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table case_judgment_information
     *
     * @mbggenerated
     */
    int countByExample(CaseJudgmentInformationExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table case_judgment_information
     *
     * @mbggenerated
     */
    int deleteByExample(CaseJudgmentInformationExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table case_judgment_information
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(CaseJudgmentInformationKey key);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table case_judgment_information
     *
     * @mbggenerated
     */
    int insert(CaseJudgmentInformation record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table case_judgment_information
     *
     * @mbggenerated
     */
    int insertSelective(CaseJudgmentInformation record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table case_judgment_information
     *
     * @mbggenerated
     */
    List<CaseJudgmentInformation> selectByExample(CaseJudgmentInformationExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table case_judgment_information
     *
     * @mbggenerated
     */
    CaseJudgmentInformation selectByPrimaryKey(CaseJudgmentInformationKey key);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table case_judgment_information
     *
     * @mbggenerated
     */
    int updateByExampleSelective(@Param("record") CaseJudgmentInformation record, @Param("example") CaseJudgmentInformationExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table case_judgment_information
     *
     * @mbggenerated
     */
    int updateByExample(@Param("record") CaseJudgmentInformation record, @Param("example") CaseJudgmentInformationExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table case_judgment_information
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(CaseJudgmentInformation record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table case_judgment_information
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(CaseJudgmentInformation record);
}