package com.zxh.ssm.module.whole.mapper;

import com.zxh.ssm.module.whole.pojo.DiseaseOutbreak;
import com.zxh.ssm.module.whole.pojo.DiseaseOutbreakExample;
import com.zxh.ssm.module.whole.pojo.DiseaseOutbreakKey;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface DiseaseOutbreakMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table disease_outbreak
     *
     * @mbggenerated
     */
    int countByExample(DiseaseOutbreakExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table disease_outbreak
     *
     * @mbggenerated
     */
    int deleteByExample(DiseaseOutbreakExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table disease_outbreak
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(DiseaseOutbreakKey key);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table disease_outbreak
     *
     * @mbggenerated
     */
    int insert(DiseaseOutbreak record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table disease_outbreak
     *
     * @mbggenerated
     */
    int insertSelective(DiseaseOutbreak record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table disease_outbreak
     *
     * @mbggenerated
     */
    List<DiseaseOutbreak> selectByExample(DiseaseOutbreakExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table disease_outbreak
     *
     * @mbggenerated
     */
    DiseaseOutbreak selectByPrimaryKey(DiseaseOutbreakKey key);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table disease_outbreak
     *
     * @mbggenerated
     */
    int updateByExampleSelective(@Param("record") DiseaseOutbreak record, @Param("example") DiseaseOutbreakExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table disease_outbreak
     *
     * @mbggenerated
     */
    int updateByExample(@Param("record") DiseaseOutbreak record, @Param("example") DiseaseOutbreakExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table disease_outbreak
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(DiseaseOutbreak record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table disease_outbreak
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(DiseaseOutbreak record);
}