package com.zxh.ssm.module.whole.mapper;

import com.zxh.ssm.module.whole.pojo.MeteorologicalStationInsformation;
import com.zxh.ssm.module.whole.pojo.MeteorologicalStationInsformationExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface MeteorologicalStationInsformationMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table meteorological_station_insformation
     *
     * @mbggenerated
     */
    int countByExample(MeteorologicalStationInsformationExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table meteorological_station_insformation
     *
     * @mbggenerated
     */
    int deleteByExample(MeteorologicalStationInsformationExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table meteorological_station_insformation
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Integer districtstationnum);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table meteorological_station_insformation
     *
     * @mbggenerated
     */
    int insert(MeteorologicalStationInsformation record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table meteorological_station_insformation
     *
     * @mbggenerated
     */
    int insertSelective(MeteorologicalStationInsformation record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table meteorological_station_insformation
     *
     * @mbggenerated
     */
    List<MeteorologicalStationInsformation> selectByExample(MeteorologicalStationInsformationExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table meteorological_station_insformation
     *
     * @mbggenerated
     */
    MeteorologicalStationInsformation selectByPrimaryKey(Integer districtstationnum);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table meteorological_station_insformation
     *
     * @mbggenerated
     */
    int updateByExampleSelective(@Param("record") MeteorologicalStationInsformation record, @Param("example") MeteorologicalStationInsformationExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table meteorological_station_insformation
     *
     * @mbggenerated
     */
    int updateByExample(@Param("record") MeteorologicalStationInsformation record, @Param("example") MeteorologicalStationInsformationExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table meteorological_station_insformation
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(MeteorologicalStationInsformation record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table meteorological_station_insformation
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(MeteorologicalStationInsformation record);
}