package com.zxh.ssm.module.whole.mapper;

import com.zxh.ssm.module.whole.pojo.PatientInformation;
import com.zxh.ssm.module.whole.pojo.PatientInformationExample;
import com.zxh.ssm.module.whole.pojo.PatientInformationKey;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface PatientInformationMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table patient_information
     *
     * @mbggenerated
     */
    int countByExample(PatientInformationExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table patient_information
     *
     * @mbggenerated
     */
    int deleteByExample(PatientInformationExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table patient_information
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(PatientInformationKey key);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table patient_information
     *
     * @mbggenerated
     */
    int insert(PatientInformation record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table patient_information
     *
     * @mbggenerated
     */
    int insertSelective(PatientInformation record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table patient_information
     *
     * @mbggenerated
     */
    List<PatientInformation> selectByExample(PatientInformationExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table patient_information
     *
     * @mbggenerated
     */
    PatientInformation selectByPrimaryKey(PatientInformationKey key);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table patient_information
     *
     * @mbggenerated
     */
    int updateByExampleSelective(@Param("record") PatientInformation record, @Param("example") PatientInformationExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table patient_information
     *
     * @mbggenerated
     */
    int updateByExample(@Param("record") PatientInformation record, @Param("example") PatientInformationExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table patient_information
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(PatientInformation record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table patient_information
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(PatientInformation record);
}