package com.zxh.ssm.module.whole.mapper;

import com.zxh.ssm.module.whole.pojo.StandardPosition;
import com.zxh.ssm.module.whole.pojo.StandardPositionExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface StandardPositionMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table standard_position
     *
     * @mbggenerated
     */
    int countByExample(StandardPositionExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table standard_position
     *
     * @mbggenerated
     */
    int deleteByExample(StandardPositionExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table standard_position
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table standard_position
     *
     * @mbggenerated
     */
    int insert(StandardPosition record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table standard_position
     *
     * @mbggenerated
     */
    int insertSelective(StandardPosition record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table standard_position
     *
     * @mbggenerated
     */
    List<StandardPosition> selectByExample(StandardPositionExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table standard_position
     *
     * @mbggenerated
     */
    StandardPosition selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table standard_position
     *
     * @mbggenerated
     */
    int updateByExampleSelective(@Param("record") StandardPosition record, @Param("example") StandardPositionExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table standard_position
     *
     * @mbggenerated
     */
    int updateByExample(@Param("record") StandardPosition record, @Param("example") StandardPositionExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table standard_position
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(StandardPosition record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table standard_position
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(StandardPosition record);
}