package com.generator.pojo;

public class CardInformation {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column card_information.cardID
     *
     * @mbggenerated
     */
    private Integer cardid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column card_information.cardNumber
     *
     * @mbggenerated
     */
    private String cardnumber;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column card_information.cardMode
     *
     * @mbggenerated
     */
    private String cardmode;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column card_information.cardID
     *
     * @return the value of card_information.cardID
     *
     * @mbggenerated
     */
    public Integer getCardid() {
        return cardid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column card_information.cardID
     *
     * @param cardid the value for card_information.cardID
     *
     * @mbggenerated
     */
    public void setCardid(Integer cardid) {
        this.cardid = cardid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column card_information.cardNumber
     *
     * @return the value of card_information.cardNumber
     *
     * @mbggenerated
     */
    public String getCardnumber() {
        return cardnumber;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column card_information.cardNumber
     *
     * @param cardnumber the value for card_information.cardNumber
     *
     * @mbggenerated
     */
    public void setCardnumber(String cardnumber) {
        this.cardnumber = cardnumber == null ? null : cardnumber.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column card_information.cardMode
     *
     * @return the value of card_information.cardMode
     *
     * @mbggenerated
     */
    public String getCardmode() {
        return cardmode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column card_information.cardMode
     *
     * @param cardmode the value for card_information.cardMode
     *
     * @mbggenerated
     */
    public void setCardmode(String cardmode) {
        this.cardmode = cardmode == null ? null : cardmode.trim();
    }
}