package com.generator.pojo;

public class InputDisease {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column input_disease.cardID
     *
     * @mbggenerated
     */
    private Integer cardid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column input_disease.whetherInputCases
     *
     * @mbggenerated
     */
    private Integer whetherinputcases;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column input_disease.dateOnSet
     *
     * @mbggenerated
     */
    private Integer dateonset;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column input_disease.firstDay
     *
     * @mbggenerated
     */
    private Integer firstday;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column input_disease.nDay
     *
     * @mbggenerated
     */
    private Integer nday;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column input_disease.cardID
     *
     * @return the value of input_disease.cardID
     *
     * @mbggenerated
     */
    public Integer getCardid() {
        return cardid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column input_disease.cardID
     *
     * @param cardid the value for input_disease.cardID
     *
     * @mbggenerated
     */
    public void setCardid(Integer cardid) {
        this.cardid = cardid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column input_disease.whetherInputCases
     *
     * @return the value of input_disease.whetherInputCases
     *
     * @mbggenerated
     */
    public Integer getWhetherinputcases() {
        return whetherinputcases;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column input_disease.whetherInputCases
     *
     * @param whetherinputcases the value for input_disease.whetherInputCases
     *
     * @mbggenerated
     */
    public void setWhetherinputcases(Integer whetherinputcases) {
        this.whetherinputcases = whetherinputcases;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column input_disease.dateOnSet
     *
     * @return the value of input_disease.dateOnSet
     *
     * @mbggenerated
     */
    public Integer getDateonset() {
        return dateonset;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column input_disease.dateOnSet
     *
     * @param dateonset the value for input_disease.dateOnSet
     *
     * @mbggenerated
     */
    public void setDateonset(Integer dateonset) {
        this.dateonset = dateonset;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column input_disease.firstDay
     *
     * @return the value of input_disease.firstDay
     *
     * @mbggenerated
     */
    public Integer getFirstday() {
        return firstday;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column input_disease.firstDay
     *
     * @param firstday the value for input_disease.firstDay
     *
     * @mbggenerated
     */
    public void setFirstday(Integer firstday) {
        this.firstday = firstday;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column input_disease.nDay
     *
     * @return the value of input_disease.nDay
     *
     * @mbggenerated
     */
    public Integer getNday() {
        return nday;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column input_disease.nDay
     *
     * @param nday the value for input_disease.nDay
     *
     * @mbggenerated
     */
    public void setNday(Integer nday) {
        this.nday = nday;
    }
}