package com.generator.pojo;

import java.util.ArrayList;
import java.util.List;

public class PatientInformationExample {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table patient_information
     *
     * @mbggenerated
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table patient_information
     *
     * @mbggenerated
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table patient_information
     *
     * @mbggenerated
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table patient_information
     *
     * @mbggenerated
     */
    public PatientInformationExample() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table patient_information
     *
     * @mbggenerated
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table patient_information
     *
     * @mbggenerated
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table patient_information
     *
     * @mbggenerated
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table patient_information
     *
     * @mbggenerated
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table patient_information
     *
     * @mbggenerated
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table patient_information
     *
     * @mbggenerated
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table patient_information
     *
     * @mbggenerated
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table patient_information
     *
     * @mbggenerated
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table patient_information
     *
     * @mbggenerated
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table patient_information
     *
     * @mbggenerated
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table patient_information
     *
     * @mbggenerated
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andDatainputyearIsNull() {
            addCriterion("dataInputYear is null");
            return (Criteria) this;
        }

        public Criteria andDatainputyearIsNotNull() {
            addCriterion("dataInputYear is not null");
            return (Criteria) this;
        }

        public Criteria andDatainputyearEqualTo(Integer value) {
            addCriterion("dataInputYear =", value, "datainputyear");
            return (Criteria) this;
        }

        public Criteria andDatainputyearNotEqualTo(Integer value) {
            addCriterion("dataInputYear <>", value, "datainputyear");
            return (Criteria) this;
        }

        public Criteria andDatainputyearGreaterThan(Integer value) {
            addCriterion("dataInputYear >", value, "datainputyear");
            return (Criteria) this;
        }

        public Criteria andDatainputyearGreaterThanOrEqualTo(Integer value) {
            addCriterion("dataInputYear >=", value, "datainputyear");
            return (Criteria) this;
        }

        public Criteria andDatainputyearLessThan(Integer value) {
            addCriterion("dataInputYear <", value, "datainputyear");
            return (Criteria) this;
        }

        public Criteria andDatainputyearLessThanOrEqualTo(Integer value) {
            addCriterion("dataInputYear <=", value, "datainputyear");
            return (Criteria) this;
        }

        public Criteria andDatainputyearIn(List<Integer> values) {
            addCriterion("dataInputYear in", values, "datainputyear");
            return (Criteria) this;
        }

        public Criteria andDatainputyearNotIn(List<Integer> values) {
            addCriterion("dataInputYear not in", values, "datainputyear");
            return (Criteria) this;
        }

        public Criteria andDatainputyearBetween(Integer value1, Integer value2) {
            addCriterion("dataInputYear between", value1, value2, "datainputyear");
            return (Criteria) this;
        }

        public Criteria andDatainputyearNotBetween(Integer value1, Integer value2) {
            addCriterion("dataInputYear not between", value1, value2, "datainputyear");
            return (Criteria) this;
        }

        public Criteria andCardidIsNull() {
            addCriterion("cardID is null");
            return (Criteria) this;
        }

        public Criteria andCardidIsNotNull() {
            addCriterion("cardID is not null");
            return (Criteria) this;
        }

        public Criteria andCardidEqualTo(Integer value) {
            addCriterion("cardID =", value, "cardid");
            return (Criteria) this;
        }

        public Criteria andCardidNotEqualTo(Integer value) {
            addCriterion("cardID <>", value, "cardid");
            return (Criteria) this;
        }

        public Criteria andCardidGreaterThan(Integer value) {
            addCriterion("cardID >", value, "cardid");
            return (Criteria) this;
        }

        public Criteria andCardidGreaterThanOrEqualTo(Integer value) {
            addCriterion("cardID >=", value, "cardid");
            return (Criteria) this;
        }

        public Criteria andCardidLessThan(Integer value) {
            addCriterion("cardID <", value, "cardid");
            return (Criteria) this;
        }

        public Criteria andCardidLessThanOrEqualTo(Integer value) {
            addCriterion("cardID <=", value, "cardid");
            return (Criteria) this;
        }

        public Criteria andCardidIn(List<Integer> values) {
            addCriterion("cardID in", values, "cardid");
            return (Criteria) this;
        }

        public Criteria andCardidNotIn(List<Integer> values) {
            addCriterion("cardID not in", values, "cardid");
            return (Criteria) this;
        }

        public Criteria andCardidBetween(Integer value1, Integer value2) {
            addCriterion("cardID between", value1, value2, "cardid");
            return (Criteria) this;
        }

        public Criteria andCardidNotBetween(Integer value1, Integer value2) {
            addCriterion("cardID not between", value1, value2, "cardid");
            return (Criteria) this;
        }

        public Criteria andPanameIsNull() {
            addCriterion("paName is null");
            return (Criteria) this;
        }

        public Criteria andPanameIsNotNull() {
            addCriterion("paName is not null");
            return (Criteria) this;
        }

        public Criteria andPanameEqualTo(String value) {
            addCriterion("paName =", value, "paname");
            return (Criteria) this;
        }

        public Criteria andPanameNotEqualTo(String value) {
            addCriterion("paName <>", value, "paname");
            return (Criteria) this;
        }

        public Criteria andPanameGreaterThan(String value) {
            addCriterion("paName >", value, "paname");
            return (Criteria) this;
        }

        public Criteria andPanameGreaterThanOrEqualTo(String value) {
            addCriterion("paName >=", value, "paname");
            return (Criteria) this;
        }

        public Criteria andPanameLessThan(String value) {
            addCriterion("paName <", value, "paname");
            return (Criteria) this;
        }

        public Criteria andPanameLessThanOrEqualTo(String value) {
            addCriterion("paName <=", value, "paname");
            return (Criteria) this;
        }

        public Criteria andPanameLike(String value) {
            addCriterion("paName like", value, "paname");
            return (Criteria) this;
        }

        public Criteria andPanameNotLike(String value) {
            addCriterion("paName not like", value, "paname");
            return (Criteria) this;
        }

        public Criteria andPanameIn(List<String> values) {
            addCriterion("paName in", values, "paname");
            return (Criteria) this;
        }

        public Criteria andPanameNotIn(List<String> values) {
            addCriterion("paName not in", values, "paname");
            return (Criteria) this;
        }

        public Criteria andPanameBetween(String value1, String value2) {
            addCriterion("paName between", value1, value2, "paname");
            return (Criteria) this;
        }

        public Criteria andPanameNotBetween(String value1, String value2) {
            addCriterion("paName not between", value1, value2, "paname");
            return (Criteria) this;
        }

        public Criteria andPasexIsNull() {
            addCriterion("paSex is null");
            return (Criteria) this;
        }

        public Criteria andPasexIsNotNull() {
            addCriterion("paSex is not null");
            return (Criteria) this;
        }

        public Criteria andPasexEqualTo(String value) {
            addCriterion("paSex =", value, "pasex");
            return (Criteria) this;
        }

        public Criteria andPasexNotEqualTo(String value) {
            addCriterion("paSex <>", value, "pasex");
            return (Criteria) this;
        }

        public Criteria andPasexGreaterThan(String value) {
            addCriterion("paSex >", value, "pasex");
            return (Criteria) this;
        }

        public Criteria andPasexGreaterThanOrEqualTo(String value) {
            addCriterion("paSex >=", value, "pasex");
            return (Criteria) this;
        }

        public Criteria andPasexLessThan(String value) {
            addCriterion("paSex <", value, "pasex");
            return (Criteria) this;
        }

        public Criteria andPasexLessThanOrEqualTo(String value) {
            addCriterion("paSex <=", value, "pasex");
            return (Criteria) this;
        }

        public Criteria andPasexLike(String value) {
            addCriterion("paSex like", value, "pasex");
            return (Criteria) this;
        }

        public Criteria andPasexNotLike(String value) {
            addCriterion("paSex not like", value, "pasex");
            return (Criteria) this;
        }

        public Criteria andPasexIn(List<String> values) {
            addCriterion("paSex in", values, "pasex");
            return (Criteria) this;
        }

        public Criteria andPasexNotIn(List<String> values) {
            addCriterion("paSex not in", values, "pasex");
            return (Criteria) this;
        }

        public Criteria andPasexBetween(String value1, String value2) {
            addCriterion("paSex between", value1, value2, "pasex");
            return (Criteria) this;
        }

        public Criteria andPasexNotBetween(String value1, String value2) {
            addCriterion("paSex not between", value1, value2, "pasex");
            return (Criteria) this;
        }

        public Criteria andPabirthIsNull() {
            addCriterion("paBirth is null");
            return (Criteria) this;
        }

        public Criteria andPabirthIsNotNull() {
            addCriterion("paBirth is not null");
            return (Criteria) this;
        }

        public Criteria andPabirthEqualTo(String value) {
            addCriterion("paBirth =", value, "pabirth");
            return (Criteria) this;
        }

        public Criteria andPabirthNotEqualTo(String value) {
            addCriterion("paBirth <>", value, "pabirth");
            return (Criteria) this;
        }

        public Criteria andPabirthGreaterThan(String value) {
            addCriterion("paBirth >", value, "pabirth");
            return (Criteria) this;
        }

        public Criteria andPabirthGreaterThanOrEqualTo(String value) {
            addCriterion("paBirth >=", value, "pabirth");
            return (Criteria) this;
        }

        public Criteria andPabirthLessThan(String value) {
            addCriterion("paBirth <", value, "pabirth");
            return (Criteria) this;
        }

        public Criteria andPabirthLessThanOrEqualTo(String value) {
            addCriterion("paBirth <=", value, "pabirth");
            return (Criteria) this;
        }

        public Criteria andPabirthLike(String value) {
            addCriterion("paBirth like", value, "pabirth");
            return (Criteria) this;
        }

        public Criteria andPabirthNotLike(String value) {
            addCriterion("paBirth not like", value, "pabirth");
            return (Criteria) this;
        }

        public Criteria andPabirthIn(List<String> values) {
            addCriterion("paBirth in", values, "pabirth");
            return (Criteria) this;
        }

        public Criteria andPabirthNotIn(List<String> values) {
            addCriterion("paBirth not in", values, "pabirth");
            return (Criteria) this;
        }

        public Criteria andPabirthBetween(String value1, String value2) {
            addCriterion("paBirth between", value1, value2, "pabirth");
            return (Criteria) this;
        }

        public Criteria andPabirthNotBetween(String value1, String value2) {
            addCriterion("paBirth not between", value1, value2, "pabirth");
            return (Criteria) this;
        }

        public Criteria andPaageIsNull() {
            addCriterion("paAge is null");
            return (Criteria) this;
        }

        public Criteria andPaageIsNotNull() {
            addCriterion("paAge is not null");
            return (Criteria) this;
        }

        public Criteria andPaageEqualTo(String value) {
            addCriterion("paAge =", value, "paage");
            return (Criteria) this;
        }

        public Criteria andPaageNotEqualTo(String value) {
            addCriterion("paAge <>", value, "paage");
            return (Criteria) this;
        }

        public Criteria andPaageGreaterThan(String value) {
            addCriterion("paAge >", value, "paage");
            return (Criteria) this;
        }

        public Criteria andPaageGreaterThanOrEqualTo(String value) {
            addCriterion("paAge >=", value, "paage");
            return (Criteria) this;
        }

        public Criteria andPaageLessThan(String value) {
            addCriterion("paAge <", value, "paage");
            return (Criteria) this;
        }

        public Criteria andPaageLessThanOrEqualTo(String value) {
            addCriterion("paAge <=", value, "paage");
            return (Criteria) this;
        }

        public Criteria andPaageLike(String value) {
            addCriterion("paAge like", value, "paage");
            return (Criteria) this;
        }

        public Criteria andPaageNotLike(String value) {
            addCriterion("paAge not like", value, "paage");
            return (Criteria) this;
        }

        public Criteria andPaageIn(List<String> values) {
            addCriterion("paAge in", values, "paage");
            return (Criteria) this;
        }

        public Criteria andPaageNotIn(List<String> values) {
            addCriterion("paAge not in", values, "paage");
            return (Criteria) this;
        }

        public Criteria andPaageBetween(String value1, String value2) {
            addCriterion("paAge between", value1, value2, "paage");
            return (Criteria) this;
        }

        public Criteria andPaageNotBetween(String value1, String value2) {
            addCriterion("paAge not between", value1, value2, "paage");
            return (Criteria) this;
        }

        public Criteria andPaworkplaceIsNull() {
            addCriterion("paWorkPlace is null");
            return (Criteria) this;
        }

        public Criteria andPaworkplaceIsNotNull() {
            addCriterion("paWorkPlace is not null");
            return (Criteria) this;
        }

        public Criteria andPaworkplaceEqualTo(String value) {
            addCriterion("paWorkPlace =", value, "paworkplace");
            return (Criteria) this;
        }

        public Criteria andPaworkplaceNotEqualTo(String value) {
            addCriterion("paWorkPlace <>", value, "paworkplace");
            return (Criteria) this;
        }

        public Criteria andPaworkplaceGreaterThan(String value) {
            addCriterion("paWorkPlace >", value, "paworkplace");
            return (Criteria) this;
        }

        public Criteria andPaworkplaceGreaterThanOrEqualTo(String value) {
            addCriterion("paWorkPlace >=", value, "paworkplace");
            return (Criteria) this;
        }

        public Criteria andPaworkplaceLessThan(String value) {
            addCriterion("paWorkPlace <", value, "paworkplace");
            return (Criteria) this;
        }

        public Criteria andPaworkplaceLessThanOrEqualTo(String value) {
            addCriterion("paWorkPlace <=", value, "paworkplace");
            return (Criteria) this;
        }

        public Criteria andPaworkplaceLike(String value) {
            addCriterion("paWorkPlace like", value, "paworkplace");
            return (Criteria) this;
        }

        public Criteria andPaworkplaceNotLike(String value) {
            addCriterion("paWorkPlace not like", value, "paworkplace");
            return (Criteria) this;
        }

        public Criteria andPaworkplaceIn(List<String> values) {
            addCriterion("paWorkPlace in", values, "paworkplace");
            return (Criteria) this;
        }

        public Criteria andPaworkplaceNotIn(List<String> values) {
            addCriterion("paWorkPlace not in", values, "paworkplace");
            return (Criteria) this;
        }

        public Criteria andPaworkplaceBetween(String value1, String value2) {
            addCriterion("paWorkPlace between", value1, value2, "paworkplace");
            return (Criteria) this;
        }

        public Criteria andPaworkplaceNotBetween(String value1, String value2) {
            addCriterion("paWorkPlace not between", value1, value2, "paworkplace");
            return (Criteria) this;
        }

        public Criteria andPatelIsNull() {
            addCriterion("paTel is null");
            return (Criteria) this;
        }

        public Criteria andPatelIsNotNull() {
            addCriterion("paTel is not null");
            return (Criteria) this;
        }

        public Criteria andPatelEqualTo(String value) {
            addCriterion("paTel =", value, "patel");
            return (Criteria) this;
        }

        public Criteria andPatelNotEqualTo(String value) {
            addCriterion("paTel <>", value, "patel");
            return (Criteria) this;
        }

        public Criteria andPatelGreaterThan(String value) {
            addCriterion("paTel >", value, "patel");
            return (Criteria) this;
        }

        public Criteria andPatelGreaterThanOrEqualTo(String value) {
            addCriterion("paTel >=", value, "patel");
            return (Criteria) this;
        }

        public Criteria andPatelLessThan(String value) {
            addCriterion("paTel <", value, "patel");
            return (Criteria) this;
        }

        public Criteria andPatelLessThanOrEqualTo(String value) {
            addCriterion("paTel <=", value, "patel");
            return (Criteria) this;
        }

        public Criteria andPatelLike(String value) {
            addCriterion("paTel like", value, "patel");
            return (Criteria) this;
        }

        public Criteria andPatelNotLike(String value) {
            addCriterion("paTel not like", value, "patel");
            return (Criteria) this;
        }

        public Criteria andPatelIn(List<String> values) {
            addCriterion("paTel in", values, "patel");
            return (Criteria) this;
        }

        public Criteria andPatelNotIn(List<String> values) {
            addCriterion("paTel not in", values, "patel");
            return (Criteria) this;
        }

        public Criteria andPatelBetween(String value1, String value2) {
            addCriterion("paTel between", value1, value2, "patel");
            return (Criteria) this;
        }

        public Criteria andPatelNotBetween(String value1, String value2) {
            addCriterion("paTel not between", value1, value2, "patel");
            return (Criteria) this;
        }

        public Criteria andPaprofessionIsNull() {
            addCriterion("paProfession is null");
            return (Criteria) this;
        }

        public Criteria andPaprofessionIsNotNull() {
            addCriterion("paProfession is not null");
            return (Criteria) this;
        }

        public Criteria andPaprofessionEqualTo(String value) {
            addCriterion("paProfession =", value, "paprofession");
            return (Criteria) this;
        }

        public Criteria andPaprofessionNotEqualTo(String value) {
            addCriterion("paProfession <>", value, "paprofession");
            return (Criteria) this;
        }

        public Criteria andPaprofessionGreaterThan(String value) {
            addCriterion("paProfession >", value, "paprofession");
            return (Criteria) this;
        }

        public Criteria andPaprofessionGreaterThanOrEqualTo(String value) {
            addCriterion("paProfession >=", value, "paprofession");
            return (Criteria) this;
        }

        public Criteria andPaprofessionLessThan(String value) {
            addCriterion("paProfession <", value, "paprofession");
            return (Criteria) this;
        }

        public Criteria andPaprofessionLessThanOrEqualTo(String value) {
            addCriterion("paProfession <=", value, "paprofession");
            return (Criteria) this;
        }

        public Criteria andPaprofessionLike(String value) {
            addCriterion("paProfession like", value, "paprofession");
            return (Criteria) this;
        }

        public Criteria andPaprofessionNotLike(String value) {
            addCriterion("paProfession not like", value, "paprofession");
            return (Criteria) this;
        }

        public Criteria andPaprofessionIn(List<String> values) {
            addCriterion("paProfession in", values, "paprofession");
            return (Criteria) this;
        }

        public Criteria andPaprofessionNotIn(List<String> values) {
            addCriterion("paProfession not in", values, "paprofession");
            return (Criteria) this;
        }

        public Criteria andPaprofessionBetween(String value1, String value2) {
            addCriterion("paProfession between", value1, value2, "paprofession");
            return (Criteria) this;
        }

        public Criteria andPaprofessionNotBetween(String value1, String value2) {
            addCriterion("paProfession not between", value1, value2, "paprofession");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table patient_information
     *
     * @mbggenerated do_not_delete_during_merge
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table patient_information
     *
     * @mbggenerated
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}