package com.generator.pojo;

public class ReportunitInformation {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column reportunit_information.cardID
     *
     * @mbggenerated
     */
    private Integer cardid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column reportunit_information.codeReportArea
     *
     * @mbggenerated
     */
    private Integer codereportarea;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column reportunit_information.reportUnit
     *
     * @mbggenerated
     */
    private String reportunit;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column reportunit_information.typeUnit
     *
     * @mbggenerated
     */
    private String typeunit;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column reportunit_information.entryTimeReportCard
     *
     * @mbggenerated
     */
    private String entrytimereportcard;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column reportunit_information.userRecordCard
     *
     * @mbggenerated
     */
    private String userrecordcard;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column reportunit_information.unitUserRecordCard
     *
     * @mbggenerated
     */
    private String unituserrecordcard;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column reportunit_information.timeCountyAudit
     *
     * @mbggenerated
     */
    private String timecountyaudit;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column reportunit_information.timeCityAudit
     *
     * @mbggenerated
     */
    private String timecityaudit;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column reportunit_information.timeProvincesAudit
     *
     * @mbggenerated
     */
    private String timeprovincesaudit;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column reportunit_information.statusAudit
     *
     * @mbggenerated
     */
    private String statusaudit;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column reportunit_information.timeCorrectionReport
     *
     * @mbggenerated
     */
    private String timecorrectionreport;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column reportunit_information.timeCorrectionFinal
     *
     * @mbggenerated
     */
    private String timecorrectionfinal;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column reportunit_information.timeDeathFinal
     *
     * @mbggenerated
     */
    private String timedeathfinal;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column reportunit_information.userCorrection
     *
     * @mbggenerated
     */
    private String usercorrection;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column reportunit_information.unitUserCorrection
     *
     * @mbggenerated
     */
    private String unitusercorrection;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column reportunit_information.timeDelete
     *
     * @mbggenerated
     */
    private String timedelete;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column reportunit_information.userDelete
     *
     * @mbggenerated
     */
    private String userdelete;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column reportunit_information.unitUserDelete
     *
     * @mbggenerated
     */
    private String unituserdelete;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column reportunit_information.reasonDelete
     *
     * @mbggenerated
     */
    private String reasondelete;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column reportunit_information.cardID
     *
     * @return the value of reportunit_information.cardID
     *
     * @mbggenerated
     */
    public Integer getCardid() {
        return cardid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column reportunit_information.cardID
     *
     * @param cardid the value for reportunit_information.cardID
     *
     * @mbggenerated
     */
    public void setCardid(Integer cardid) {
        this.cardid = cardid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column reportunit_information.codeReportArea
     *
     * @return the value of reportunit_information.codeReportArea
     *
     * @mbggenerated
     */
    public Integer getCodereportarea() {
        return codereportarea;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column reportunit_information.codeReportArea
     *
     * @param codereportarea the value for reportunit_information.codeReportArea
     *
     * @mbggenerated
     */
    public void setCodereportarea(Integer codereportarea) {
        this.codereportarea = codereportarea;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column reportunit_information.reportUnit
     *
     * @return the value of reportunit_information.reportUnit
     *
     * @mbggenerated
     */
    public String getReportunit() {
        return reportunit;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column reportunit_information.reportUnit
     *
     * @param reportunit the value for reportunit_information.reportUnit
     *
     * @mbggenerated
     */
    public void setReportunit(String reportunit) {
        this.reportunit = reportunit == null ? null : reportunit.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column reportunit_information.typeUnit
     *
     * @return the value of reportunit_information.typeUnit
     *
     * @mbggenerated
     */
    public String getTypeunit() {
        return typeunit;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column reportunit_information.typeUnit
     *
     * @param typeunit the value for reportunit_information.typeUnit
     *
     * @mbggenerated
     */
    public void setTypeunit(String typeunit) {
        this.typeunit = typeunit == null ? null : typeunit.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column reportunit_information.entryTimeReportCard
     *
     * @return the value of reportunit_information.entryTimeReportCard
     *
     * @mbggenerated
     */
    public String getEntrytimereportcard() {
        return entrytimereportcard;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column reportunit_information.entryTimeReportCard
     *
     * @param entrytimereportcard the value for reportunit_information.entryTimeReportCard
     *
     * @mbggenerated
     */
    public void setEntrytimereportcard(String entrytimereportcard) {
        this.entrytimereportcard = entrytimereportcard == null ? null : entrytimereportcard.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column reportunit_information.userRecordCard
     *
     * @return the value of reportunit_information.userRecordCard
     *
     * @mbggenerated
     */
    public String getUserrecordcard() {
        return userrecordcard;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column reportunit_information.userRecordCard
     *
     * @param userrecordcard the value for reportunit_information.userRecordCard
     *
     * @mbggenerated
     */
    public void setUserrecordcard(String userrecordcard) {
        this.userrecordcard = userrecordcard == null ? null : userrecordcard.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column reportunit_information.unitUserRecordCard
     *
     * @return the value of reportunit_information.unitUserRecordCard
     *
     * @mbggenerated
     */
    public String getUnituserrecordcard() {
        return unituserrecordcard;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column reportunit_information.unitUserRecordCard
     *
     * @param unituserrecordcard the value for reportunit_information.unitUserRecordCard
     *
     * @mbggenerated
     */
    public void setUnituserrecordcard(String unituserrecordcard) {
        this.unituserrecordcard = unituserrecordcard == null ? null : unituserrecordcard.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column reportunit_information.timeCountyAudit
     *
     * @return the value of reportunit_information.timeCountyAudit
     *
     * @mbggenerated
     */
    public String getTimecountyaudit() {
        return timecountyaudit;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column reportunit_information.timeCountyAudit
     *
     * @param timecountyaudit the value for reportunit_information.timeCountyAudit
     *
     * @mbggenerated
     */
    public void setTimecountyaudit(String timecountyaudit) {
        this.timecountyaudit = timecountyaudit == null ? null : timecountyaudit.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column reportunit_information.timeCityAudit
     *
     * @return the value of reportunit_information.timeCityAudit
     *
     * @mbggenerated
     */
    public String getTimecityaudit() {
        return timecityaudit;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column reportunit_information.timeCityAudit
     *
     * @param timecityaudit the value for reportunit_information.timeCityAudit
     *
     * @mbggenerated
     */
    public void setTimecityaudit(String timecityaudit) {
        this.timecityaudit = timecityaudit == null ? null : timecityaudit.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column reportunit_information.timeProvincesAudit
     *
     * @return the value of reportunit_information.timeProvincesAudit
     *
     * @mbggenerated
     */
    public String getTimeprovincesaudit() {
        return timeprovincesaudit;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column reportunit_information.timeProvincesAudit
     *
     * @param timeprovincesaudit the value for reportunit_information.timeProvincesAudit
     *
     * @mbggenerated
     */
    public void setTimeprovincesaudit(String timeprovincesaudit) {
        this.timeprovincesaudit = timeprovincesaudit == null ? null : timeprovincesaudit.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column reportunit_information.statusAudit
     *
     * @return the value of reportunit_information.statusAudit
     *
     * @mbggenerated
     */
    public String getStatusaudit() {
        return statusaudit;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column reportunit_information.statusAudit
     *
     * @param statusaudit the value for reportunit_information.statusAudit
     *
     * @mbggenerated
     */
    public void setStatusaudit(String statusaudit) {
        this.statusaudit = statusaudit == null ? null : statusaudit.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column reportunit_information.timeCorrectionReport
     *
     * @return the value of reportunit_information.timeCorrectionReport
     *
     * @mbggenerated
     */
    public String getTimecorrectionreport() {
        return timecorrectionreport;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column reportunit_information.timeCorrectionReport
     *
     * @param timecorrectionreport the value for reportunit_information.timeCorrectionReport
     *
     * @mbggenerated
     */
    public void setTimecorrectionreport(String timecorrectionreport) {
        this.timecorrectionreport = timecorrectionreport == null ? null : timecorrectionreport.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column reportunit_information.timeCorrectionFinal
     *
     * @return the value of reportunit_information.timeCorrectionFinal
     *
     * @mbggenerated
     */
    public String getTimecorrectionfinal() {
        return timecorrectionfinal;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column reportunit_information.timeCorrectionFinal
     *
     * @param timecorrectionfinal the value for reportunit_information.timeCorrectionFinal
     *
     * @mbggenerated
     */
    public void setTimecorrectionfinal(String timecorrectionfinal) {
        this.timecorrectionfinal = timecorrectionfinal == null ? null : timecorrectionfinal.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column reportunit_information.timeDeathFinal
     *
     * @return the value of reportunit_information.timeDeathFinal
     *
     * @mbggenerated
     */
    public String getTimedeathfinal() {
        return timedeathfinal;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column reportunit_information.timeDeathFinal
     *
     * @param timedeathfinal the value for reportunit_information.timeDeathFinal
     *
     * @mbggenerated
     */
    public void setTimedeathfinal(String timedeathfinal) {
        this.timedeathfinal = timedeathfinal == null ? null : timedeathfinal.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column reportunit_information.userCorrection
     *
     * @return the value of reportunit_information.userCorrection
     *
     * @mbggenerated
     */
    public String getUsercorrection() {
        return usercorrection;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column reportunit_information.userCorrection
     *
     * @param usercorrection the value for reportunit_information.userCorrection
     *
     * @mbggenerated
     */
    public void setUsercorrection(String usercorrection) {
        this.usercorrection = usercorrection == null ? null : usercorrection.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column reportunit_information.unitUserCorrection
     *
     * @return the value of reportunit_information.unitUserCorrection
     *
     * @mbggenerated
     */
    public String getUnitusercorrection() {
        return unitusercorrection;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column reportunit_information.unitUserCorrection
     *
     * @param unitusercorrection the value for reportunit_information.unitUserCorrection
     *
     * @mbggenerated
     */
    public void setUnitusercorrection(String unitusercorrection) {
        this.unitusercorrection = unitusercorrection == null ? null : unitusercorrection.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column reportunit_information.timeDelete
     *
     * @return the value of reportunit_information.timeDelete
     *
     * @mbggenerated
     */
    public String getTimedelete() {
        return timedelete;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column reportunit_information.timeDelete
     *
     * @param timedelete the value for reportunit_information.timeDelete
     *
     * @mbggenerated
     */
    public void setTimedelete(String timedelete) {
        this.timedelete = timedelete == null ? null : timedelete.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column reportunit_information.userDelete
     *
     * @return the value of reportunit_information.userDelete
     *
     * @mbggenerated
     */
    public String getUserdelete() {
        return userdelete;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column reportunit_information.userDelete
     *
     * @param userdelete the value for reportunit_information.userDelete
     *
     * @mbggenerated
     */
    public void setUserdelete(String userdelete) {
        this.userdelete = userdelete == null ? null : userdelete.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column reportunit_information.unitUserDelete
     *
     * @return the value of reportunit_information.unitUserDelete
     *
     * @mbggenerated
     */
    public String getUnituserdelete() {
        return unituserdelete;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column reportunit_information.unitUserDelete
     *
     * @param unituserdelete the value for reportunit_information.unitUserDelete
     *
     * @mbggenerated
     */
    public void setUnituserdelete(String unituserdelete) {
        this.unituserdelete = unituserdelete == null ? null : unituserdelete.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column reportunit_information.reasonDelete
     *
     * @return the value of reportunit_information.reasonDelete
     *
     * @mbggenerated
     */
    public String getReasondelete() {
        return reasondelete;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column reportunit_information.reasonDelete
     *
     * @param reasondelete the value for reportunit_information.reasonDelete
     *
     * @mbggenerated
     */
    public void setReasondelete(String reasondelete) {
        this.reasondelete = reasondelete == null ? null : reasondelete.trim();
    }
}