package com.generator.pojo;

import java.util.ArrayList;
import java.util.List;

public class ReportunitInformationExample {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table reportunit_information
     *
     * @mbggenerated
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table reportunit_information
     *
     * @mbggenerated
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table reportunit_information
     *
     * @mbggenerated
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table reportunit_information
     *
     * @mbggenerated
     */
    public ReportunitInformationExample() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table reportunit_information
     *
     * @mbggenerated
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table reportunit_information
     *
     * @mbggenerated
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table reportunit_information
     *
     * @mbggenerated
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table reportunit_information
     *
     * @mbggenerated
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table reportunit_information
     *
     * @mbggenerated
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table reportunit_information
     *
     * @mbggenerated
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table reportunit_information
     *
     * @mbggenerated
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table reportunit_information
     *
     * @mbggenerated
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table reportunit_information
     *
     * @mbggenerated
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table reportunit_information
     *
     * @mbggenerated
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table reportunit_information
     *
     * @mbggenerated
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andCardidIsNull() {
            addCriterion("cardID is null");
            return (Criteria) this;
        }

        public Criteria andCardidIsNotNull() {
            addCriterion("cardID is not null");
            return (Criteria) this;
        }

        public Criteria andCardidEqualTo(Integer value) {
            addCriterion("cardID =", value, "cardid");
            return (Criteria) this;
        }

        public Criteria andCardidNotEqualTo(Integer value) {
            addCriterion("cardID <>", value, "cardid");
            return (Criteria) this;
        }

        public Criteria andCardidGreaterThan(Integer value) {
            addCriterion("cardID >", value, "cardid");
            return (Criteria) this;
        }

        public Criteria andCardidGreaterThanOrEqualTo(Integer value) {
            addCriterion("cardID >=", value, "cardid");
            return (Criteria) this;
        }

        public Criteria andCardidLessThan(Integer value) {
            addCriterion("cardID <", value, "cardid");
            return (Criteria) this;
        }

        public Criteria andCardidLessThanOrEqualTo(Integer value) {
            addCriterion("cardID <=", value, "cardid");
            return (Criteria) this;
        }

        public Criteria andCardidIn(List<Integer> values) {
            addCriterion("cardID in", values, "cardid");
            return (Criteria) this;
        }

        public Criteria andCardidNotIn(List<Integer> values) {
            addCriterion("cardID not in", values, "cardid");
            return (Criteria) this;
        }

        public Criteria andCardidBetween(Integer value1, Integer value2) {
            addCriterion("cardID between", value1, value2, "cardid");
            return (Criteria) this;
        }

        public Criteria andCardidNotBetween(Integer value1, Integer value2) {
            addCriterion("cardID not between", value1, value2, "cardid");
            return (Criteria) this;
        }

        public Criteria andCodereportareaIsNull() {
            addCriterion("codeReportArea is null");
            return (Criteria) this;
        }

        public Criteria andCodereportareaIsNotNull() {
            addCriterion("codeReportArea is not null");
            return (Criteria) this;
        }

        public Criteria andCodereportareaEqualTo(Integer value) {
            addCriterion("codeReportArea =", value, "codereportarea");
            return (Criteria) this;
        }

        public Criteria andCodereportareaNotEqualTo(Integer value) {
            addCriterion("codeReportArea <>", value, "codereportarea");
            return (Criteria) this;
        }

        public Criteria andCodereportareaGreaterThan(Integer value) {
            addCriterion("codeReportArea >", value, "codereportarea");
            return (Criteria) this;
        }

        public Criteria andCodereportareaGreaterThanOrEqualTo(Integer value) {
            addCriterion("codeReportArea >=", value, "codereportarea");
            return (Criteria) this;
        }

        public Criteria andCodereportareaLessThan(Integer value) {
            addCriterion("codeReportArea <", value, "codereportarea");
            return (Criteria) this;
        }

        public Criteria andCodereportareaLessThanOrEqualTo(Integer value) {
            addCriterion("codeReportArea <=", value, "codereportarea");
            return (Criteria) this;
        }

        public Criteria andCodereportareaIn(List<Integer> values) {
            addCriterion("codeReportArea in", values, "codereportarea");
            return (Criteria) this;
        }

        public Criteria andCodereportareaNotIn(List<Integer> values) {
            addCriterion("codeReportArea not in", values, "codereportarea");
            return (Criteria) this;
        }

        public Criteria andCodereportareaBetween(Integer value1, Integer value2) {
            addCriterion("codeReportArea between", value1, value2, "codereportarea");
            return (Criteria) this;
        }

        public Criteria andCodereportareaNotBetween(Integer value1, Integer value2) {
            addCriterion("codeReportArea not between", value1, value2, "codereportarea");
            return (Criteria) this;
        }

        public Criteria andReportunitIsNull() {
            addCriterion("reportUnit is null");
            return (Criteria) this;
        }

        public Criteria andReportunitIsNotNull() {
            addCriterion("reportUnit is not null");
            return (Criteria) this;
        }

        public Criteria andReportunitEqualTo(String value) {
            addCriterion("reportUnit =", value, "reportunit");
            return (Criteria) this;
        }

        public Criteria andReportunitNotEqualTo(String value) {
            addCriterion("reportUnit <>", value, "reportunit");
            return (Criteria) this;
        }

        public Criteria andReportunitGreaterThan(String value) {
            addCriterion("reportUnit >", value, "reportunit");
            return (Criteria) this;
        }

        public Criteria andReportunitGreaterThanOrEqualTo(String value) {
            addCriterion("reportUnit >=", value, "reportunit");
            return (Criteria) this;
        }

        public Criteria andReportunitLessThan(String value) {
            addCriterion("reportUnit <", value, "reportunit");
            return (Criteria) this;
        }

        public Criteria andReportunitLessThanOrEqualTo(String value) {
            addCriterion("reportUnit <=", value, "reportunit");
            return (Criteria) this;
        }

        public Criteria andReportunitLike(String value) {
            addCriterion("reportUnit like", value, "reportunit");
            return (Criteria) this;
        }

        public Criteria andReportunitNotLike(String value) {
            addCriterion("reportUnit not like", value, "reportunit");
            return (Criteria) this;
        }

        public Criteria andReportunitIn(List<String> values) {
            addCriterion("reportUnit in", values, "reportunit");
            return (Criteria) this;
        }

        public Criteria andReportunitNotIn(List<String> values) {
            addCriterion("reportUnit not in", values, "reportunit");
            return (Criteria) this;
        }

        public Criteria andReportunitBetween(String value1, String value2) {
            addCriterion("reportUnit between", value1, value2, "reportunit");
            return (Criteria) this;
        }

        public Criteria andReportunitNotBetween(String value1, String value2) {
            addCriterion("reportUnit not between", value1, value2, "reportunit");
            return (Criteria) this;
        }

        public Criteria andTypeunitIsNull() {
            addCriterion("typeUnit is null");
            return (Criteria) this;
        }

        public Criteria andTypeunitIsNotNull() {
            addCriterion("typeUnit is not null");
            return (Criteria) this;
        }

        public Criteria andTypeunitEqualTo(String value) {
            addCriterion("typeUnit =", value, "typeunit");
            return (Criteria) this;
        }

        public Criteria andTypeunitNotEqualTo(String value) {
            addCriterion("typeUnit <>", value, "typeunit");
            return (Criteria) this;
        }

        public Criteria andTypeunitGreaterThan(String value) {
            addCriterion("typeUnit >", value, "typeunit");
            return (Criteria) this;
        }

        public Criteria andTypeunitGreaterThanOrEqualTo(String value) {
            addCriterion("typeUnit >=", value, "typeunit");
            return (Criteria) this;
        }

        public Criteria andTypeunitLessThan(String value) {
            addCriterion("typeUnit <", value, "typeunit");
            return (Criteria) this;
        }

        public Criteria andTypeunitLessThanOrEqualTo(String value) {
            addCriterion("typeUnit <=", value, "typeunit");
            return (Criteria) this;
        }

        public Criteria andTypeunitLike(String value) {
            addCriterion("typeUnit like", value, "typeunit");
            return (Criteria) this;
        }

        public Criteria andTypeunitNotLike(String value) {
            addCriterion("typeUnit not like", value, "typeunit");
            return (Criteria) this;
        }

        public Criteria andTypeunitIn(List<String> values) {
            addCriterion("typeUnit in", values, "typeunit");
            return (Criteria) this;
        }

        public Criteria andTypeunitNotIn(List<String> values) {
            addCriterion("typeUnit not in", values, "typeunit");
            return (Criteria) this;
        }

        public Criteria andTypeunitBetween(String value1, String value2) {
            addCriterion("typeUnit between", value1, value2, "typeunit");
            return (Criteria) this;
        }

        public Criteria andTypeunitNotBetween(String value1, String value2) {
            addCriterion("typeUnit not between", value1, value2, "typeunit");
            return (Criteria) this;
        }

        public Criteria andEntrytimereportcardIsNull() {
            addCriterion("entryTimeReportCard is null");
            return (Criteria) this;
        }

        public Criteria andEntrytimereportcardIsNotNull() {
            addCriterion("entryTimeReportCard is not null");
            return (Criteria) this;
        }

        public Criteria andEntrytimereportcardEqualTo(String value) {
            addCriterion("entryTimeReportCard =", value, "entrytimereportcard");
            return (Criteria) this;
        }

        public Criteria andEntrytimereportcardNotEqualTo(String value) {
            addCriterion("entryTimeReportCard <>", value, "entrytimereportcard");
            return (Criteria) this;
        }

        public Criteria andEntrytimereportcardGreaterThan(String value) {
            addCriterion("entryTimeReportCard >", value, "entrytimereportcard");
            return (Criteria) this;
        }

        public Criteria andEntrytimereportcardGreaterThanOrEqualTo(String value) {
            addCriterion("entryTimeReportCard >=", value, "entrytimereportcard");
            return (Criteria) this;
        }

        public Criteria andEntrytimereportcardLessThan(String value) {
            addCriterion("entryTimeReportCard <", value, "entrytimereportcard");
            return (Criteria) this;
        }

        public Criteria andEntrytimereportcardLessThanOrEqualTo(String value) {
            addCriterion("entryTimeReportCard <=", value, "entrytimereportcard");
            return (Criteria) this;
        }

        public Criteria andEntrytimereportcardLike(String value) {
            addCriterion("entryTimeReportCard like", value, "entrytimereportcard");
            return (Criteria) this;
        }

        public Criteria andEntrytimereportcardNotLike(String value) {
            addCriterion("entryTimeReportCard not like", value, "entrytimereportcard");
            return (Criteria) this;
        }

        public Criteria andEntrytimereportcardIn(List<String> values) {
            addCriterion("entryTimeReportCard in", values, "entrytimereportcard");
            return (Criteria) this;
        }

        public Criteria andEntrytimereportcardNotIn(List<String> values) {
            addCriterion("entryTimeReportCard not in", values, "entrytimereportcard");
            return (Criteria) this;
        }

        public Criteria andEntrytimereportcardBetween(String value1, String value2) {
            addCriterion("entryTimeReportCard between", value1, value2, "entrytimereportcard");
            return (Criteria) this;
        }

        public Criteria andEntrytimereportcardNotBetween(String value1, String value2) {
            addCriterion("entryTimeReportCard not between", value1, value2, "entrytimereportcard");
            return (Criteria) this;
        }

        public Criteria andUserrecordcardIsNull() {
            addCriterion("userRecordCard is null");
            return (Criteria) this;
        }

        public Criteria andUserrecordcardIsNotNull() {
            addCriterion("userRecordCard is not null");
            return (Criteria) this;
        }

        public Criteria andUserrecordcardEqualTo(String value) {
            addCriterion("userRecordCard =", value, "userrecordcard");
            return (Criteria) this;
        }

        public Criteria andUserrecordcardNotEqualTo(String value) {
            addCriterion("userRecordCard <>", value, "userrecordcard");
            return (Criteria) this;
        }

        public Criteria andUserrecordcardGreaterThan(String value) {
            addCriterion("userRecordCard >", value, "userrecordcard");
            return (Criteria) this;
        }

        public Criteria andUserrecordcardGreaterThanOrEqualTo(String value) {
            addCriterion("userRecordCard >=", value, "userrecordcard");
            return (Criteria) this;
        }

        public Criteria andUserrecordcardLessThan(String value) {
            addCriterion("userRecordCard <", value, "userrecordcard");
            return (Criteria) this;
        }

        public Criteria andUserrecordcardLessThanOrEqualTo(String value) {
            addCriterion("userRecordCard <=", value, "userrecordcard");
            return (Criteria) this;
        }

        public Criteria andUserrecordcardLike(String value) {
            addCriterion("userRecordCard like", value, "userrecordcard");
            return (Criteria) this;
        }

        public Criteria andUserrecordcardNotLike(String value) {
            addCriterion("userRecordCard not like", value, "userrecordcard");
            return (Criteria) this;
        }

        public Criteria andUserrecordcardIn(List<String> values) {
            addCriterion("userRecordCard in", values, "userrecordcard");
            return (Criteria) this;
        }

        public Criteria andUserrecordcardNotIn(List<String> values) {
            addCriterion("userRecordCard not in", values, "userrecordcard");
            return (Criteria) this;
        }

        public Criteria andUserrecordcardBetween(String value1, String value2) {
            addCriterion("userRecordCard between", value1, value2, "userrecordcard");
            return (Criteria) this;
        }

        public Criteria andUserrecordcardNotBetween(String value1, String value2) {
            addCriterion("userRecordCard not between", value1, value2, "userrecordcard");
            return (Criteria) this;
        }

        public Criteria andUnituserrecordcardIsNull() {
            addCriterion("unitUserRecordCard is null");
            return (Criteria) this;
        }

        public Criteria andUnituserrecordcardIsNotNull() {
            addCriterion("unitUserRecordCard is not null");
            return (Criteria) this;
        }

        public Criteria andUnituserrecordcardEqualTo(String value) {
            addCriterion("unitUserRecordCard =", value, "unituserrecordcard");
            return (Criteria) this;
        }

        public Criteria andUnituserrecordcardNotEqualTo(String value) {
            addCriterion("unitUserRecordCard <>", value, "unituserrecordcard");
            return (Criteria) this;
        }

        public Criteria andUnituserrecordcardGreaterThan(String value) {
            addCriterion("unitUserRecordCard >", value, "unituserrecordcard");
            return (Criteria) this;
        }

        public Criteria andUnituserrecordcardGreaterThanOrEqualTo(String value) {
            addCriterion("unitUserRecordCard >=", value, "unituserrecordcard");
            return (Criteria) this;
        }

        public Criteria andUnituserrecordcardLessThan(String value) {
            addCriterion("unitUserRecordCard <", value, "unituserrecordcard");
            return (Criteria) this;
        }

        public Criteria andUnituserrecordcardLessThanOrEqualTo(String value) {
            addCriterion("unitUserRecordCard <=", value, "unituserrecordcard");
            return (Criteria) this;
        }

        public Criteria andUnituserrecordcardLike(String value) {
            addCriterion("unitUserRecordCard like", value, "unituserrecordcard");
            return (Criteria) this;
        }

        public Criteria andUnituserrecordcardNotLike(String value) {
            addCriterion("unitUserRecordCard not like", value, "unituserrecordcard");
            return (Criteria) this;
        }

        public Criteria andUnituserrecordcardIn(List<String> values) {
            addCriterion("unitUserRecordCard in", values, "unituserrecordcard");
            return (Criteria) this;
        }

        public Criteria andUnituserrecordcardNotIn(List<String> values) {
            addCriterion("unitUserRecordCard not in", values, "unituserrecordcard");
            return (Criteria) this;
        }

        public Criteria andUnituserrecordcardBetween(String value1, String value2) {
            addCriterion("unitUserRecordCard between", value1, value2, "unituserrecordcard");
            return (Criteria) this;
        }

        public Criteria andUnituserrecordcardNotBetween(String value1, String value2) {
            addCriterion("unitUserRecordCard not between", value1, value2, "unituserrecordcard");
            return (Criteria) this;
        }

        public Criteria andTimecountyauditIsNull() {
            addCriterion("timeCountyAudit is null");
            return (Criteria) this;
        }

        public Criteria andTimecountyauditIsNotNull() {
            addCriterion("timeCountyAudit is not null");
            return (Criteria) this;
        }

        public Criteria andTimecountyauditEqualTo(String value) {
            addCriterion("timeCountyAudit =", value, "timecountyaudit");
            return (Criteria) this;
        }

        public Criteria andTimecountyauditNotEqualTo(String value) {
            addCriterion("timeCountyAudit <>", value, "timecountyaudit");
            return (Criteria) this;
        }

        public Criteria andTimecountyauditGreaterThan(String value) {
            addCriterion("timeCountyAudit >", value, "timecountyaudit");
            return (Criteria) this;
        }

        public Criteria andTimecountyauditGreaterThanOrEqualTo(String value) {
            addCriterion("timeCountyAudit >=", value, "timecountyaudit");
            return (Criteria) this;
        }

        public Criteria andTimecountyauditLessThan(String value) {
            addCriterion("timeCountyAudit <", value, "timecountyaudit");
            return (Criteria) this;
        }

        public Criteria andTimecountyauditLessThanOrEqualTo(String value) {
            addCriterion("timeCountyAudit <=", value, "timecountyaudit");
            return (Criteria) this;
        }

        public Criteria andTimecountyauditLike(String value) {
            addCriterion("timeCountyAudit like", value, "timecountyaudit");
            return (Criteria) this;
        }

        public Criteria andTimecountyauditNotLike(String value) {
            addCriterion("timeCountyAudit not like", value, "timecountyaudit");
            return (Criteria) this;
        }

        public Criteria andTimecountyauditIn(List<String> values) {
            addCriterion("timeCountyAudit in", values, "timecountyaudit");
            return (Criteria) this;
        }

        public Criteria andTimecountyauditNotIn(List<String> values) {
            addCriterion("timeCountyAudit not in", values, "timecountyaudit");
            return (Criteria) this;
        }

        public Criteria andTimecountyauditBetween(String value1, String value2) {
            addCriterion("timeCountyAudit between", value1, value2, "timecountyaudit");
            return (Criteria) this;
        }

        public Criteria andTimecountyauditNotBetween(String value1, String value2) {
            addCriterion("timeCountyAudit not between", value1, value2, "timecountyaudit");
            return (Criteria) this;
        }

        public Criteria andTimecityauditIsNull() {
            addCriterion("timeCityAudit is null");
            return (Criteria) this;
        }

        public Criteria andTimecityauditIsNotNull() {
            addCriterion("timeCityAudit is not null");
            return (Criteria) this;
        }

        public Criteria andTimecityauditEqualTo(String value) {
            addCriterion("timeCityAudit =", value, "timecityaudit");
            return (Criteria) this;
        }

        public Criteria andTimecityauditNotEqualTo(String value) {
            addCriterion("timeCityAudit <>", value, "timecityaudit");
            return (Criteria) this;
        }

        public Criteria andTimecityauditGreaterThan(String value) {
            addCriterion("timeCityAudit >", value, "timecityaudit");
            return (Criteria) this;
        }

        public Criteria andTimecityauditGreaterThanOrEqualTo(String value) {
            addCriterion("timeCityAudit >=", value, "timecityaudit");
            return (Criteria) this;
        }

        public Criteria andTimecityauditLessThan(String value) {
            addCriterion("timeCityAudit <", value, "timecityaudit");
            return (Criteria) this;
        }

        public Criteria andTimecityauditLessThanOrEqualTo(String value) {
            addCriterion("timeCityAudit <=", value, "timecityaudit");
            return (Criteria) this;
        }

        public Criteria andTimecityauditLike(String value) {
            addCriterion("timeCityAudit like", value, "timecityaudit");
            return (Criteria) this;
        }

        public Criteria andTimecityauditNotLike(String value) {
            addCriterion("timeCityAudit not like", value, "timecityaudit");
            return (Criteria) this;
        }

        public Criteria andTimecityauditIn(List<String> values) {
            addCriterion("timeCityAudit in", values, "timecityaudit");
            return (Criteria) this;
        }

        public Criteria andTimecityauditNotIn(List<String> values) {
            addCriterion("timeCityAudit not in", values, "timecityaudit");
            return (Criteria) this;
        }

        public Criteria andTimecityauditBetween(String value1, String value2) {
            addCriterion("timeCityAudit between", value1, value2, "timecityaudit");
            return (Criteria) this;
        }

        public Criteria andTimecityauditNotBetween(String value1, String value2) {
            addCriterion("timeCityAudit not between", value1, value2, "timecityaudit");
            return (Criteria) this;
        }

        public Criteria andTimeprovincesauditIsNull() {
            addCriterion("timeProvincesAudit is null");
            return (Criteria) this;
        }

        public Criteria andTimeprovincesauditIsNotNull() {
            addCriterion("timeProvincesAudit is not null");
            return (Criteria) this;
        }

        public Criteria andTimeprovincesauditEqualTo(String value) {
            addCriterion("timeProvincesAudit =", value, "timeprovincesaudit");
            return (Criteria) this;
        }

        public Criteria andTimeprovincesauditNotEqualTo(String value) {
            addCriterion("timeProvincesAudit <>", value, "timeprovincesaudit");
            return (Criteria) this;
        }

        public Criteria andTimeprovincesauditGreaterThan(String value) {
            addCriterion("timeProvincesAudit >", value, "timeprovincesaudit");
            return (Criteria) this;
        }

        public Criteria andTimeprovincesauditGreaterThanOrEqualTo(String value) {
            addCriterion("timeProvincesAudit >=", value, "timeprovincesaudit");
            return (Criteria) this;
        }

        public Criteria andTimeprovincesauditLessThan(String value) {
            addCriterion("timeProvincesAudit <", value, "timeprovincesaudit");
            return (Criteria) this;
        }

        public Criteria andTimeprovincesauditLessThanOrEqualTo(String value) {
            addCriterion("timeProvincesAudit <=", value, "timeprovincesaudit");
            return (Criteria) this;
        }

        public Criteria andTimeprovincesauditLike(String value) {
            addCriterion("timeProvincesAudit like", value, "timeprovincesaudit");
            return (Criteria) this;
        }

        public Criteria andTimeprovincesauditNotLike(String value) {
            addCriterion("timeProvincesAudit not like", value, "timeprovincesaudit");
            return (Criteria) this;
        }

        public Criteria andTimeprovincesauditIn(List<String> values) {
            addCriterion("timeProvincesAudit in", values, "timeprovincesaudit");
            return (Criteria) this;
        }

        public Criteria andTimeprovincesauditNotIn(List<String> values) {
            addCriterion("timeProvincesAudit not in", values, "timeprovincesaudit");
            return (Criteria) this;
        }

        public Criteria andTimeprovincesauditBetween(String value1, String value2) {
            addCriterion("timeProvincesAudit between", value1, value2, "timeprovincesaudit");
            return (Criteria) this;
        }

        public Criteria andTimeprovincesauditNotBetween(String value1, String value2) {
            addCriterion("timeProvincesAudit not between", value1, value2, "timeprovincesaudit");
            return (Criteria) this;
        }

        public Criteria andStatusauditIsNull() {
            addCriterion("statusAudit is null");
            return (Criteria) this;
        }

        public Criteria andStatusauditIsNotNull() {
            addCriterion("statusAudit is not null");
            return (Criteria) this;
        }

        public Criteria andStatusauditEqualTo(String value) {
            addCriterion("statusAudit =", value, "statusaudit");
            return (Criteria) this;
        }

        public Criteria andStatusauditNotEqualTo(String value) {
            addCriterion("statusAudit <>", value, "statusaudit");
            return (Criteria) this;
        }

        public Criteria andStatusauditGreaterThan(String value) {
            addCriterion("statusAudit >", value, "statusaudit");
            return (Criteria) this;
        }

        public Criteria andStatusauditGreaterThanOrEqualTo(String value) {
            addCriterion("statusAudit >=", value, "statusaudit");
            return (Criteria) this;
        }

        public Criteria andStatusauditLessThan(String value) {
            addCriterion("statusAudit <", value, "statusaudit");
            return (Criteria) this;
        }

        public Criteria andStatusauditLessThanOrEqualTo(String value) {
            addCriterion("statusAudit <=", value, "statusaudit");
            return (Criteria) this;
        }

        public Criteria andStatusauditLike(String value) {
            addCriterion("statusAudit like", value, "statusaudit");
            return (Criteria) this;
        }

        public Criteria andStatusauditNotLike(String value) {
            addCriterion("statusAudit not like", value, "statusaudit");
            return (Criteria) this;
        }

        public Criteria andStatusauditIn(List<String> values) {
            addCriterion("statusAudit in", values, "statusaudit");
            return (Criteria) this;
        }

        public Criteria andStatusauditNotIn(List<String> values) {
            addCriterion("statusAudit not in", values, "statusaudit");
            return (Criteria) this;
        }

        public Criteria andStatusauditBetween(String value1, String value2) {
            addCriterion("statusAudit between", value1, value2, "statusaudit");
            return (Criteria) this;
        }

        public Criteria andStatusauditNotBetween(String value1, String value2) {
            addCriterion("statusAudit not between", value1, value2, "statusaudit");
            return (Criteria) this;
        }

        public Criteria andTimecorrectionreportIsNull() {
            addCriterion("timeCorrectionReport is null");
            return (Criteria) this;
        }

        public Criteria andTimecorrectionreportIsNotNull() {
            addCriterion("timeCorrectionReport is not null");
            return (Criteria) this;
        }

        public Criteria andTimecorrectionreportEqualTo(String value) {
            addCriterion("timeCorrectionReport =", value, "timecorrectionreport");
            return (Criteria) this;
        }

        public Criteria andTimecorrectionreportNotEqualTo(String value) {
            addCriterion("timeCorrectionReport <>", value, "timecorrectionreport");
            return (Criteria) this;
        }

        public Criteria andTimecorrectionreportGreaterThan(String value) {
            addCriterion("timeCorrectionReport >", value, "timecorrectionreport");
            return (Criteria) this;
        }

        public Criteria andTimecorrectionreportGreaterThanOrEqualTo(String value) {
            addCriterion("timeCorrectionReport >=", value, "timecorrectionreport");
            return (Criteria) this;
        }

        public Criteria andTimecorrectionreportLessThan(String value) {
            addCriterion("timeCorrectionReport <", value, "timecorrectionreport");
            return (Criteria) this;
        }

        public Criteria andTimecorrectionreportLessThanOrEqualTo(String value) {
            addCriterion("timeCorrectionReport <=", value, "timecorrectionreport");
            return (Criteria) this;
        }

        public Criteria andTimecorrectionreportLike(String value) {
            addCriterion("timeCorrectionReport like", value, "timecorrectionreport");
            return (Criteria) this;
        }

        public Criteria andTimecorrectionreportNotLike(String value) {
            addCriterion("timeCorrectionReport not like", value, "timecorrectionreport");
            return (Criteria) this;
        }

        public Criteria andTimecorrectionreportIn(List<String> values) {
            addCriterion("timeCorrectionReport in", values, "timecorrectionreport");
            return (Criteria) this;
        }

        public Criteria andTimecorrectionreportNotIn(List<String> values) {
            addCriterion("timeCorrectionReport not in", values, "timecorrectionreport");
            return (Criteria) this;
        }

        public Criteria andTimecorrectionreportBetween(String value1, String value2) {
            addCriterion("timeCorrectionReport between", value1, value2, "timecorrectionreport");
            return (Criteria) this;
        }

        public Criteria andTimecorrectionreportNotBetween(String value1, String value2) {
            addCriterion("timeCorrectionReport not between", value1, value2, "timecorrectionreport");
            return (Criteria) this;
        }

        public Criteria andTimecorrectionfinalIsNull() {
            addCriterion("timeCorrectionFinal is null");
            return (Criteria) this;
        }

        public Criteria andTimecorrectionfinalIsNotNull() {
            addCriterion("timeCorrectionFinal is not null");
            return (Criteria) this;
        }

        public Criteria andTimecorrectionfinalEqualTo(String value) {
            addCriterion("timeCorrectionFinal =", value, "timecorrectionfinal");
            return (Criteria) this;
        }

        public Criteria andTimecorrectionfinalNotEqualTo(String value) {
            addCriterion("timeCorrectionFinal <>", value, "timecorrectionfinal");
            return (Criteria) this;
        }

        public Criteria andTimecorrectionfinalGreaterThan(String value) {
            addCriterion("timeCorrectionFinal >", value, "timecorrectionfinal");
            return (Criteria) this;
        }

        public Criteria andTimecorrectionfinalGreaterThanOrEqualTo(String value) {
            addCriterion("timeCorrectionFinal >=", value, "timecorrectionfinal");
            return (Criteria) this;
        }

        public Criteria andTimecorrectionfinalLessThan(String value) {
            addCriterion("timeCorrectionFinal <", value, "timecorrectionfinal");
            return (Criteria) this;
        }

        public Criteria andTimecorrectionfinalLessThanOrEqualTo(String value) {
            addCriterion("timeCorrectionFinal <=", value, "timecorrectionfinal");
            return (Criteria) this;
        }

        public Criteria andTimecorrectionfinalLike(String value) {
            addCriterion("timeCorrectionFinal like", value, "timecorrectionfinal");
            return (Criteria) this;
        }

        public Criteria andTimecorrectionfinalNotLike(String value) {
            addCriterion("timeCorrectionFinal not like", value, "timecorrectionfinal");
            return (Criteria) this;
        }

        public Criteria andTimecorrectionfinalIn(List<String> values) {
            addCriterion("timeCorrectionFinal in", values, "timecorrectionfinal");
            return (Criteria) this;
        }

        public Criteria andTimecorrectionfinalNotIn(List<String> values) {
            addCriterion("timeCorrectionFinal not in", values, "timecorrectionfinal");
            return (Criteria) this;
        }

        public Criteria andTimecorrectionfinalBetween(String value1, String value2) {
            addCriterion("timeCorrectionFinal between", value1, value2, "timecorrectionfinal");
            return (Criteria) this;
        }

        public Criteria andTimecorrectionfinalNotBetween(String value1, String value2) {
            addCriterion("timeCorrectionFinal not between", value1, value2, "timecorrectionfinal");
            return (Criteria) this;
        }

        public Criteria andTimedeathfinalIsNull() {
            addCriterion("timeDeathFinal is null");
            return (Criteria) this;
        }

        public Criteria andTimedeathfinalIsNotNull() {
            addCriterion("timeDeathFinal is not null");
            return (Criteria) this;
        }

        public Criteria andTimedeathfinalEqualTo(String value) {
            addCriterion("timeDeathFinal =", value, "timedeathfinal");
            return (Criteria) this;
        }

        public Criteria andTimedeathfinalNotEqualTo(String value) {
            addCriterion("timeDeathFinal <>", value, "timedeathfinal");
            return (Criteria) this;
        }

        public Criteria andTimedeathfinalGreaterThan(String value) {
            addCriterion("timeDeathFinal >", value, "timedeathfinal");
            return (Criteria) this;
        }

        public Criteria andTimedeathfinalGreaterThanOrEqualTo(String value) {
            addCriterion("timeDeathFinal >=", value, "timedeathfinal");
            return (Criteria) this;
        }

        public Criteria andTimedeathfinalLessThan(String value) {
            addCriterion("timeDeathFinal <", value, "timedeathfinal");
            return (Criteria) this;
        }

        public Criteria andTimedeathfinalLessThanOrEqualTo(String value) {
            addCriterion("timeDeathFinal <=", value, "timedeathfinal");
            return (Criteria) this;
        }

        public Criteria andTimedeathfinalLike(String value) {
            addCriterion("timeDeathFinal like", value, "timedeathfinal");
            return (Criteria) this;
        }

        public Criteria andTimedeathfinalNotLike(String value) {
            addCriterion("timeDeathFinal not like", value, "timedeathfinal");
            return (Criteria) this;
        }

        public Criteria andTimedeathfinalIn(List<String> values) {
            addCriterion("timeDeathFinal in", values, "timedeathfinal");
            return (Criteria) this;
        }

        public Criteria andTimedeathfinalNotIn(List<String> values) {
            addCriterion("timeDeathFinal not in", values, "timedeathfinal");
            return (Criteria) this;
        }

        public Criteria andTimedeathfinalBetween(String value1, String value2) {
            addCriterion("timeDeathFinal between", value1, value2, "timedeathfinal");
            return (Criteria) this;
        }

        public Criteria andTimedeathfinalNotBetween(String value1, String value2) {
            addCriterion("timeDeathFinal not between", value1, value2, "timedeathfinal");
            return (Criteria) this;
        }

        public Criteria andUsercorrectionIsNull() {
            addCriterion("userCorrection is null");
            return (Criteria) this;
        }

        public Criteria andUsercorrectionIsNotNull() {
            addCriterion("userCorrection is not null");
            return (Criteria) this;
        }

        public Criteria andUsercorrectionEqualTo(String value) {
            addCriterion("userCorrection =", value, "usercorrection");
            return (Criteria) this;
        }

        public Criteria andUsercorrectionNotEqualTo(String value) {
            addCriterion("userCorrection <>", value, "usercorrection");
            return (Criteria) this;
        }

        public Criteria andUsercorrectionGreaterThan(String value) {
            addCriterion("userCorrection >", value, "usercorrection");
            return (Criteria) this;
        }

        public Criteria andUsercorrectionGreaterThanOrEqualTo(String value) {
            addCriterion("userCorrection >=", value, "usercorrection");
            return (Criteria) this;
        }

        public Criteria andUsercorrectionLessThan(String value) {
            addCriterion("userCorrection <", value, "usercorrection");
            return (Criteria) this;
        }

        public Criteria andUsercorrectionLessThanOrEqualTo(String value) {
            addCriterion("userCorrection <=", value, "usercorrection");
            return (Criteria) this;
        }

        public Criteria andUsercorrectionLike(String value) {
            addCriterion("userCorrection like", value, "usercorrection");
            return (Criteria) this;
        }

        public Criteria andUsercorrectionNotLike(String value) {
            addCriterion("userCorrection not like", value, "usercorrection");
            return (Criteria) this;
        }

        public Criteria andUsercorrectionIn(List<String> values) {
            addCriterion("userCorrection in", values, "usercorrection");
            return (Criteria) this;
        }

        public Criteria andUsercorrectionNotIn(List<String> values) {
            addCriterion("userCorrection not in", values, "usercorrection");
            return (Criteria) this;
        }

        public Criteria andUsercorrectionBetween(String value1, String value2) {
            addCriterion("userCorrection between", value1, value2, "usercorrection");
            return (Criteria) this;
        }

        public Criteria andUsercorrectionNotBetween(String value1, String value2) {
            addCriterion("userCorrection not between", value1, value2, "usercorrection");
            return (Criteria) this;
        }

        public Criteria andUnitusercorrectionIsNull() {
            addCriterion("unitUserCorrection is null");
            return (Criteria) this;
        }

        public Criteria andUnitusercorrectionIsNotNull() {
            addCriterion("unitUserCorrection is not null");
            return (Criteria) this;
        }

        public Criteria andUnitusercorrectionEqualTo(String value) {
            addCriterion("unitUserCorrection =", value, "unitusercorrection");
            return (Criteria) this;
        }

        public Criteria andUnitusercorrectionNotEqualTo(String value) {
            addCriterion("unitUserCorrection <>", value, "unitusercorrection");
            return (Criteria) this;
        }

        public Criteria andUnitusercorrectionGreaterThan(String value) {
            addCriterion("unitUserCorrection >", value, "unitusercorrection");
            return (Criteria) this;
        }

        public Criteria andUnitusercorrectionGreaterThanOrEqualTo(String value) {
            addCriterion("unitUserCorrection >=", value, "unitusercorrection");
            return (Criteria) this;
        }

        public Criteria andUnitusercorrectionLessThan(String value) {
            addCriterion("unitUserCorrection <", value, "unitusercorrection");
            return (Criteria) this;
        }

        public Criteria andUnitusercorrectionLessThanOrEqualTo(String value) {
            addCriterion("unitUserCorrection <=", value, "unitusercorrection");
            return (Criteria) this;
        }

        public Criteria andUnitusercorrectionLike(String value) {
            addCriterion("unitUserCorrection like", value, "unitusercorrection");
            return (Criteria) this;
        }

        public Criteria andUnitusercorrectionNotLike(String value) {
            addCriterion("unitUserCorrection not like", value, "unitusercorrection");
            return (Criteria) this;
        }

        public Criteria andUnitusercorrectionIn(List<String> values) {
            addCriterion("unitUserCorrection in", values, "unitusercorrection");
            return (Criteria) this;
        }

        public Criteria andUnitusercorrectionNotIn(List<String> values) {
            addCriterion("unitUserCorrection not in", values, "unitusercorrection");
            return (Criteria) this;
        }

        public Criteria andUnitusercorrectionBetween(String value1, String value2) {
            addCriterion("unitUserCorrection between", value1, value2, "unitusercorrection");
            return (Criteria) this;
        }

        public Criteria andUnitusercorrectionNotBetween(String value1, String value2) {
            addCriterion("unitUserCorrection not between", value1, value2, "unitusercorrection");
            return (Criteria) this;
        }

        public Criteria andTimedeleteIsNull() {
            addCriterion("timeDelete is null");
            return (Criteria) this;
        }

        public Criteria andTimedeleteIsNotNull() {
            addCriterion("timeDelete is not null");
            return (Criteria) this;
        }

        public Criteria andTimedeleteEqualTo(String value) {
            addCriterion("timeDelete =", value, "timedelete");
            return (Criteria) this;
        }

        public Criteria andTimedeleteNotEqualTo(String value) {
            addCriterion("timeDelete <>", value, "timedelete");
            return (Criteria) this;
        }

        public Criteria andTimedeleteGreaterThan(String value) {
            addCriterion("timeDelete >", value, "timedelete");
            return (Criteria) this;
        }

        public Criteria andTimedeleteGreaterThanOrEqualTo(String value) {
            addCriterion("timeDelete >=", value, "timedelete");
            return (Criteria) this;
        }

        public Criteria andTimedeleteLessThan(String value) {
            addCriterion("timeDelete <", value, "timedelete");
            return (Criteria) this;
        }

        public Criteria andTimedeleteLessThanOrEqualTo(String value) {
            addCriterion("timeDelete <=", value, "timedelete");
            return (Criteria) this;
        }

        public Criteria andTimedeleteLike(String value) {
            addCriterion("timeDelete like", value, "timedelete");
            return (Criteria) this;
        }

        public Criteria andTimedeleteNotLike(String value) {
            addCriterion("timeDelete not like", value, "timedelete");
            return (Criteria) this;
        }

        public Criteria andTimedeleteIn(List<String> values) {
            addCriterion("timeDelete in", values, "timedelete");
            return (Criteria) this;
        }

        public Criteria andTimedeleteNotIn(List<String> values) {
            addCriterion("timeDelete not in", values, "timedelete");
            return (Criteria) this;
        }

        public Criteria andTimedeleteBetween(String value1, String value2) {
            addCriterion("timeDelete between", value1, value2, "timedelete");
            return (Criteria) this;
        }

        public Criteria andTimedeleteNotBetween(String value1, String value2) {
            addCriterion("timeDelete not between", value1, value2, "timedelete");
            return (Criteria) this;
        }

        public Criteria andUserdeleteIsNull() {
            addCriterion("userDelete is null");
            return (Criteria) this;
        }

        public Criteria andUserdeleteIsNotNull() {
            addCriterion("userDelete is not null");
            return (Criteria) this;
        }

        public Criteria andUserdeleteEqualTo(String value) {
            addCriterion("userDelete =", value, "userdelete");
            return (Criteria) this;
        }

        public Criteria andUserdeleteNotEqualTo(String value) {
            addCriterion("userDelete <>", value, "userdelete");
            return (Criteria) this;
        }

        public Criteria andUserdeleteGreaterThan(String value) {
            addCriterion("userDelete >", value, "userdelete");
            return (Criteria) this;
        }

        public Criteria andUserdeleteGreaterThanOrEqualTo(String value) {
            addCriterion("userDelete >=", value, "userdelete");
            return (Criteria) this;
        }

        public Criteria andUserdeleteLessThan(String value) {
            addCriterion("userDelete <", value, "userdelete");
            return (Criteria) this;
        }

        public Criteria andUserdeleteLessThanOrEqualTo(String value) {
            addCriterion("userDelete <=", value, "userdelete");
            return (Criteria) this;
        }

        public Criteria andUserdeleteLike(String value) {
            addCriterion("userDelete like", value, "userdelete");
            return (Criteria) this;
        }

        public Criteria andUserdeleteNotLike(String value) {
            addCriterion("userDelete not like", value, "userdelete");
            return (Criteria) this;
        }

        public Criteria andUserdeleteIn(List<String> values) {
            addCriterion("userDelete in", values, "userdelete");
            return (Criteria) this;
        }

        public Criteria andUserdeleteNotIn(List<String> values) {
            addCriterion("userDelete not in", values, "userdelete");
            return (Criteria) this;
        }

        public Criteria andUserdeleteBetween(String value1, String value2) {
            addCriterion("userDelete between", value1, value2, "userdelete");
            return (Criteria) this;
        }

        public Criteria andUserdeleteNotBetween(String value1, String value2) {
            addCriterion("userDelete not between", value1, value2, "userdelete");
            return (Criteria) this;
        }

        public Criteria andUnituserdeleteIsNull() {
            addCriterion("unitUserDelete is null");
            return (Criteria) this;
        }

        public Criteria andUnituserdeleteIsNotNull() {
            addCriterion("unitUserDelete is not null");
            return (Criteria) this;
        }

        public Criteria andUnituserdeleteEqualTo(String value) {
            addCriterion("unitUserDelete =", value, "unituserdelete");
            return (Criteria) this;
        }

        public Criteria andUnituserdeleteNotEqualTo(String value) {
            addCriterion("unitUserDelete <>", value, "unituserdelete");
            return (Criteria) this;
        }

        public Criteria andUnituserdeleteGreaterThan(String value) {
            addCriterion("unitUserDelete >", value, "unituserdelete");
            return (Criteria) this;
        }

        public Criteria andUnituserdeleteGreaterThanOrEqualTo(String value) {
            addCriterion("unitUserDelete >=", value, "unituserdelete");
            return (Criteria) this;
        }

        public Criteria andUnituserdeleteLessThan(String value) {
            addCriterion("unitUserDelete <", value, "unituserdelete");
            return (Criteria) this;
        }

        public Criteria andUnituserdeleteLessThanOrEqualTo(String value) {
            addCriterion("unitUserDelete <=", value, "unituserdelete");
            return (Criteria) this;
        }

        public Criteria andUnituserdeleteLike(String value) {
            addCriterion("unitUserDelete like", value, "unituserdelete");
            return (Criteria) this;
        }

        public Criteria andUnituserdeleteNotLike(String value) {
            addCriterion("unitUserDelete not like", value, "unituserdelete");
            return (Criteria) this;
        }

        public Criteria andUnituserdeleteIn(List<String> values) {
            addCriterion("unitUserDelete in", values, "unituserdelete");
            return (Criteria) this;
        }

        public Criteria andUnituserdeleteNotIn(List<String> values) {
            addCriterion("unitUserDelete not in", values, "unituserdelete");
            return (Criteria) this;
        }

        public Criteria andUnituserdeleteBetween(String value1, String value2) {
            addCriterion("unitUserDelete between", value1, value2, "unituserdelete");
            return (Criteria) this;
        }

        public Criteria andUnituserdeleteNotBetween(String value1, String value2) {
            addCriterion("unitUserDelete not between", value1, value2, "unituserdelete");
            return (Criteria) this;
        }

        public Criteria andReasondeleteIsNull() {
            addCriterion("reasonDelete is null");
            return (Criteria) this;
        }

        public Criteria andReasondeleteIsNotNull() {
            addCriterion("reasonDelete is not null");
            return (Criteria) this;
        }

        public Criteria andReasondeleteEqualTo(String value) {
            addCriterion("reasonDelete =", value, "reasondelete");
            return (Criteria) this;
        }

        public Criteria andReasondeleteNotEqualTo(String value) {
            addCriterion("reasonDelete <>", value, "reasondelete");
            return (Criteria) this;
        }

        public Criteria andReasondeleteGreaterThan(String value) {
            addCriterion("reasonDelete >", value, "reasondelete");
            return (Criteria) this;
        }

        public Criteria andReasondeleteGreaterThanOrEqualTo(String value) {
            addCriterion("reasonDelete >=", value, "reasondelete");
            return (Criteria) this;
        }

        public Criteria andReasondeleteLessThan(String value) {
            addCriterion("reasonDelete <", value, "reasondelete");
            return (Criteria) this;
        }

        public Criteria andReasondeleteLessThanOrEqualTo(String value) {
            addCriterion("reasonDelete <=", value, "reasondelete");
            return (Criteria) this;
        }

        public Criteria andReasondeleteLike(String value) {
            addCriterion("reasonDelete like", value, "reasondelete");
            return (Criteria) this;
        }

        public Criteria andReasondeleteNotLike(String value) {
            addCriterion("reasonDelete not like", value, "reasondelete");
            return (Criteria) this;
        }

        public Criteria andReasondeleteIn(List<String> values) {
            addCriterion("reasonDelete in", values, "reasondelete");
            return (Criteria) this;
        }

        public Criteria andReasondeleteNotIn(List<String> values) {
            addCriterion("reasonDelete not in", values, "reasondelete");
            return (Criteria) this;
        }

        public Criteria andReasondeleteBetween(String value1, String value2) {
            addCriterion("reasonDelete between", value1, value2, "reasondelete");
            return (Criteria) this;
        }

        public Criteria andReasondeleteNotBetween(String value1, String value2) {
            addCriterion("reasonDelete not between", value1, value2, "reasondelete");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table reportunit_information
     *
     * @mbggenerated do_not_delete_during_merge
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table reportunit_information
     *
     * @mbggenerated
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}