package com.generator.pojo;

import java.util.ArrayList;
import java.util.List;

public class WeatherDataExample {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table weather_data
     *
     * @mbggenerated
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table weather_data
     *
     * @mbggenerated
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table weather_data
     *
     * @mbggenerated
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table weather_data
     *
     * @mbggenerated
     */
    public WeatherDataExample() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table weather_data
     *
     * @mbggenerated
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table weather_data
     *
     * @mbggenerated
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table weather_data
     *
     * @mbggenerated
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table weather_data
     *
     * @mbggenerated
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table weather_data
     *
     * @mbggenerated
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table weather_data
     *
     * @mbggenerated
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table weather_data
     *
     * @mbggenerated
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table weather_data
     *
     * @mbggenerated
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table weather_data
     *
     * @mbggenerated
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table weather_data
     *
     * @mbggenerated
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table weather_data
     *
     * @mbggenerated
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andNumdistricystationIsNull() {
            addCriterion("numDistricyStation is null");
            return (Criteria) this;
        }

        public Criteria andNumdistricystationIsNotNull() {
            addCriterion("numDistricyStation is not null");
            return (Criteria) this;
        }

        public Criteria andNumdistricystationEqualTo(Integer value) {
            addCriterion("numDistricyStation =", value, "numdistricystation");
            return (Criteria) this;
        }

        public Criteria andNumdistricystationNotEqualTo(Integer value) {
            addCriterion("numDistricyStation <>", value, "numdistricystation");
            return (Criteria) this;
        }

        public Criteria andNumdistricystationGreaterThan(Integer value) {
            addCriterion("numDistricyStation >", value, "numdistricystation");
            return (Criteria) this;
        }

        public Criteria andNumdistricystationGreaterThanOrEqualTo(Integer value) {
            addCriterion("numDistricyStation >=", value, "numdistricystation");
            return (Criteria) this;
        }

        public Criteria andNumdistricystationLessThan(Integer value) {
            addCriterion("numDistricyStation <", value, "numdistricystation");
            return (Criteria) this;
        }

        public Criteria andNumdistricystationLessThanOrEqualTo(Integer value) {
            addCriterion("numDistricyStation <=", value, "numdistricystation");
            return (Criteria) this;
        }

        public Criteria andNumdistricystationIn(List<Integer> values) {
            addCriterion("numDistricyStation in", values, "numdistricystation");
            return (Criteria) this;
        }

        public Criteria andNumdistricystationNotIn(List<Integer> values) {
            addCriterion("numDistricyStation not in", values, "numdistricystation");
            return (Criteria) this;
        }

        public Criteria andNumdistricystationBetween(Integer value1, Integer value2) {
            addCriterion("numDistricyStation between", value1, value2, "numdistricystation");
            return (Criteria) this;
        }

        public Criteria andNumdistricystationNotBetween(Integer value1, Integer value2) {
            addCriterion("numDistricyStation not between", value1, value2, "numdistricystation");
            return (Criteria) this;
        }

        public Criteria andWeatheryearIsNull() {
            addCriterion("weatherYear is null");
            return (Criteria) this;
        }

        public Criteria andWeatheryearIsNotNull() {
            addCriterion("weatherYear is not null");
            return (Criteria) this;
        }

        public Criteria andWeatheryearEqualTo(Integer value) {
            addCriterion("weatherYear =", value, "weatheryear");
            return (Criteria) this;
        }

        public Criteria andWeatheryearNotEqualTo(Integer value) {
            addCriterion("weatherYear <>", value, "weatheryear");
            return (Criteria) this;
        }

        public Criteria andWeatheryearGreaterThan(Integer value) {
            addCriterion("weatherYear >", value, "weatheryear");
            return (Criteria) this;
        }

        public Criteria andWeatheryearGreaterThanOrEqualTo(Integer value) {
            addCriterion("weatherYear >=", value, "weatheryear");
            return (Criteria) this;
        }

        public Criteria andWeatheryearLessThan(Integer value) {
            addCriterion("weatherYear <", value, "weatheryear");
            return (Criteria) this;
        }

        public Criteria andWeatheryearLessThanOrEqualTo(Integer value) {
            addCriterion("weatherYear <=", value, "weatheryear");
            return (Criteria) this;
        }

        public Criteria andWeatheryearIn(List<Integer> values) {
            addCriterion("weatherYear in", values, "weatheryear");
            return (Criteria) this;
        }

        public Criteria andWeatheryearNotIn(List<Integer> values) {
            addCriterion("weatherYear not in", values, "weatheryear");
            return (Criteria) this;
        }

        public Criteria andWeatheryearBetween(Integer value1, Integer value2) {
            addCriterion("weatherYear between", value1, value2, "weatheryear");
            return (Criteria) this;
        }

        public Criteria andWeatheryearNotBetween(Integer value1, Integer value2) {
            addCriterion("weatherYear not between", value1, value2, "weatheryear");
            return (Criteria) this;
        }

        public Criteria andWeathermonthIsNull() {
            addCriterion("weatherMonth is null");
            return (Criteria) this;
        }

        public Criteria andWeathermonthIsNotNull() {
            addCriterion("weatherMonth is not null");
            return (Criteria) this;
        }

        public Criteria andWeathermonthEqualTo(Integer value) {
            addCriterion("weatherMonth =", value, "weathermonth");
            return (Criteria) this;
        }

        public Criteria andWeathermonthNotEqualTo(Integer value) {
            addCriterion("weatherMonth <>", value, "weathermonth");
            return (Criteria) this;
        }

        public Criteria andWeathermonthGreaterThan(Integer value) {
            addCriterion("weatherMonth >", value, "weathermonth");
            return (Criteria) this;
        }

        public Criteria andWeathermonthGreaterThanOrEqualTo(Integer value) {
            addCriterion("weatherMonth >=", value, "weathermonth");
            return (Criteria) this;
        }

        public Criteria andWeathermonthLessThan(Integer value) {
            addCriterion("weatherMonth <", value, "weathermonth");
            return (Criteria) this;
        }

        public Criteria andWeathermonthLessThanOrEqualTo(Integer value) {
            addCriterion("weatherMonth <=", value, "weathermonth");
            return (Criteria) this;
        }

        public Criteria andWeathermonthIn(List<Integer> values) {
            addCriterion("weatherMonth in", values, "weathermonth");
            return (Criteria) this;
        }

        public Criteria andWeathermonthNotIn(List<Integer> values) {
            addCriterion("weatherMonth not in", values, "weathermonth");
            return (Criteria) this;
        }

        public Criteria andWeathermonthBetween(Integer value1, Integer value2) {
            addCriterion("weatherMonth between", value1, value2, "weathermonth");
            return (Criteria) this;
        }

        public Criteria andWeathermonthNotBetween(Integer value1, Integer value2) {
            addCriterion("weatherMonth not between", value1, value2, "weathermonth");
            return (Criteria) this;
        }

        public Criteria andWeatherdayIsNull() {
            addCriterion("weatherDay is null");
            return (Criteria) this;
        }

        public Criteria andWeatherdayIsNotNull() {
            addCriterion("weatherDay is not null");
            return (Criteria) this;
        }

        public Criteria andWeatherdayEqualTo(Integer value) {
            addCriterion("weatherDay =", value, "weatherday");
            return (Criteria) this;
        }

        public Criteria andWeatherdayNotEqualTo(Integer value) {
            addCriterion("weatherDay <>", value, "weatherday");
            return (Criteria) this;
        }

        public Criteria andWeatherdayGreaterThan(Integer value) {
            addCriterion("weatherDay >", value, "weatherday");
            return (Criteria) this;
        }

        public Criteria andWeatherdayGreaterThanOrEqualTo(Integer value) {
            addCriterion("weatherDay >=", value, "weatherday");
            return (Criteria) this;
        }

        public Criteria andWeatherdayLessThan(Integer value) {
            addCriterion("weatherDay <", value, "weatherday");
            return (Criteria) this;
        }

        public Criteria andWeatherdayLessThanOrEqualTo(Integer value) {
            addCriterion("weatherDay <=", value, "weatherday");
            return (Criteria) this;
        }

        public Criteria andWeatherdayIn(List<Integer> values) {
            addCriterion("weatherDay in", values, "weatherday");
            return (Criteria) this;
        }

        public Criteria andWeatherdayNotIn(List<Integer> values) {
            addCriterion("weatherDay not in", values, "weatherday");
            return (Criteria) this;
        }

        public Criteria andWeatherdayBetween(Integer value1, Integer value2) {
            addCriterion("weatherDay between", value1, value2, "weatherday");
            return (Criteria) this;
        }

        public Criteria andWeatherdayNotBetween(Integer value1, Integer value2) {
            addCriterion("weatherDay not between", value1, value2, "weatherday");
            return (Criteria) this;
        }

        public Criteria andPrecipitation2020IsNull() {
            addCriterion("precipitation2020 is null");
            return (Criteria) this;
        }

        public Criteria andPrecipitation2020IsNotNull() {
            addCriterion("precipitation2020 is not null");
            return (Criteria) this;
        }

        public Criteria andPrecipitation2020EqualTo(Integer value) {
            addCriterion("precipitation2020 =", value, "precipitation2020");
            return (Criteria) this;
        }

        public Criteria andPrecipitation2020NotEqualTo(Integer value) {
            addCriterion("precipitation2020 <>", value, "precipitation2020");
            return (Criteria) this;
        }

        public Criteria andPrecipitation2020GreaterThan(Integer value) {
            addCriterion("precipitation2020 >", value, "precipitation2020");
            return (Criteria) this;
        }

        public Criteria andPrecipitation2020GreaterThanOrEqualTo(Integer value) {
            addCriterion("precipitation2020 >=", value, "precipitation2020");
            return (Criteria) this;
        }

        public Criteria andPrecipitation2020LessThan(Integer value) {
            addCriterion("precipitation2020 <", value, "precipitation2020");
            return (Criteria) this;
        }

        public Criteria andPrecipitation2020LessThanOrEqualTo(Integer value) {
            addCriterion("precipitation2020 <=", value, "precipitation2020");
            return (Criteria) this;
        }

        public Criteria andPrecipitation2020In(List<Integer> values) {
            addCriterion("precipitation2020 in", values, "precipitation2020");
            return (Criteria) this;
        }

        public Criteria andPrecipitation2020NotIn(List<Integer> values) {
            addCriterion("precipitation2020 not in", values, "precipitation2020");
            return (Criteria) this;
        }

        public Criteria andPrecipitation2020Between(Integer value1, Integer value2) {
            addCriterion("precipitation2020 between", value1, value2, "precipitation2020");
            return (Criteria) this;
        }

        public Criteria andPrecipitation2020NotBetween(Integer value1, Integer value2) {
            addCriterion("precipitation2020 not between", value1, value2, "precipitation2020");
            return (Criteria) this;
        }

        public Criteria andMaximumwindspeedIsNull() {
            addCriterion("maximumWindSpeed is null");
            return (Criteria) this;
        }

        public Criteria andMaximumwindspeedIsNotNull() {
            addCriterion("maximumWindSpeed is not null");
            return (Criteria) this;
        }

        public Criteria andMaximumwindspeedEqualTo(Integer value) {
            addCriterion("maximumWindSpeed =", value, "maximumwindspeed");
            return (Criteria) this;
        }

        public Criteria andMaximumwindspeedNotEqualTo(Integer value) {
            addCriterion("maximumWindSpeed <>", value, "maximumwindspeed");
            return (Criteria) this;
        }

        public Criteria andMaximumwindspeedGreaterThan(Integer value) {
            addCriterion("maximumWindSpeed >", value, "maximumwindspeed");
            return (Criteria) this;
        }

        public Criteria andMaximumwindspeedGreaterThanOrEqualTo(Integer value) {
            addCriterion("maximumWindSpeed >=", value, "maximumwindspeed");
            return (Criteria) this;
        }

        public Criteria andMaximumwindspeedLessThan(Integer value) {
            addCriterion("maximumWindSpeed <", value, "maximumwindspeed");
            return (Criteria) this;
        }

        public Criteria andMaximumwindspeedLessThanOrEqualTo(Integer value) {
            addCriterion("maximumWindSpeed <=", value, "maximumwindspeed");
            return (Criteria) this;
        }

        public Criteria andMaximumwindspeedIn(List<Integer> values) {
            addCriterion("maximumWindSpeed in", values, "maximumwindspeed");
            return (Criteria) this;
        }

        public Criteria andMaximumwindspeedNotIn(List<Integer> values) {
            addCriterion("maximumWindSpeed not in", values, "maximumwindspeed");
            return (Criteria) this;
        }

        public Criteria andMaximumwindspeedBetween(Integer value1, Integer value2) {
            addCriterion("maximumWindSpeed between", value1, value2, "maximumwindspeed");
            return (Criteria) this;
        }

        public Criteria andMaximumwindspeedNotBetween(Integer value1, Integer value2) {
            addCriterion("maximumWindSpeed not between", value1, value2, "maximumwindspeed");
            return (Criteria) this;
        }

        public Criteria andDirectionmaximumwindspeedIsNull() {
            addCriterion("directionMaximumWindSpeed is null");
            return (Criteria) this;
        }

        public Criteria andDirectionmaximumwindspeedIsNotNull() {
            addCriterion("directionMaximumWindSpeed is not null");
            return (Criteria) this;
        }

        public Criteria andDirectionmaximumwindspeedEqualTo(Integer value) {
            addCriterion("directionMaximumWindSpeed =", value, "directionmaximumwindspeed");
            return (Criteria) this;
        }

        public Criteria andDirectionmaximumwindspeedNotEqualTo(Integer value) {
            addCriterion("directionMaximumWindSpeed <>", value, "directionmaximumwindspeed");
            return (Criteria) this;
        }

        public Criteria andDirectionmaximumwindspeedGreaterThan(Integer value) {
            addCriterion("directionMaximumWindSpeed >", value, "directionmaximumwindspeed");
            return (Criteria) this;
        }

        public Criteria andDirectionmaximumwindspeedGreaterThanOrEqualTo(Integer value) {
            addCriterion("directionMaximumWindSpeed >=", value, "directionmaximumwindspeed");
            return (Criteria) this;
        }

        public Criteria andDirectionmaximumwindspeedLessThan(Integer value) {
            addCriterion("directionMaximumWindSpeed <", value, "directionmaximumwindspeed");
            return (Criteria) this;
        }

        public Criteria andDirectionmaximumwindspeedLessThanOrEqualTo(Integer value) {
            addCriterion("directionMaximumWindSpeed <=", value, "directionmaximumwindspeed");
            return (Criteria) this;
        }

        public Criteria andDirectionmaximumwindspeedIn(List<Integer> values) {
            addCriterion("directionMaximumWindSpeed in", values, "directionmaximumwindspeed");
            return (Criteria) this;
        }

        public Criteria andDirectionmaximumwindspeedNotIn(List<Integer> values) {
            addCriterion("directionMaximumWindSpeed not in", values, "directionmaximumwindspeed");
            return (Criteria) this;
        }

        public Criteria andDirectionmaximumwindspeedBetween(Integer value1, Integer value2) {
            addCriterion("directionMaximumWindSpeed between", value1, value2, "directionmaximumwindspeed");
            return (Criteria) this;
        }

        public Criteria andDirectionmaximumwindspeedNotBetween(Integer value1, Integer value2) {
            addCriterion("directionMaximumWindSpeed not between", value1, value2, "directionmaximumwindspeed");
            return (Criteria) this;
        }

        public Criteria andAvepressureIsNull() {
            addCriterion("avePressure is null");
            return (Criteria) this;
        }

        public Criteria andAvepressureIsNotNull() {
            addCriterion("avePressure is not null");
            return (Criteria) this;
        }

        public Criteria andAvepressureEqualTo(Integer value) {
            addCriterion("avePressure =", value, "avepressure");
            return (Criteria) this;
        }

        public Criteria andAvepressureNotEqualTo(Integer value) {
            addCriterion("avePressure <>", value, "avepressure");
            return (Criteria) this;
        }

        public Criteria andAvepressureGreaterThan(Integer value) {
            addCriterion("avePressure >", value, "avepressure");
            return (Criteria) this;
        }

        public Criteria andAvepressureGreaterThanOrEqualTo(Integer value) {
            addCriterion("avePressure >=", value, "avepressure");
            return (Criteria) this;
        }

        public Criteria andAvepressureLessThan(Integer value) {
            addCriterion("avePressure <", value, "avepressure");
            return (Criteria) this;
        }

        public Criteria andAvepressureLessThanOrEqualTo(Integer value) {
            addCriterion("avePressure <=", value, "avepressure");
            return (Criteria) this;
        }

        public Criteria andAvepressureIn(List<Integer> values) {
            addCriterion("avePressure in", values, "avepressure");
            return (Criteria) this;
        }

        public Criteria andAvepressureNotIn(List<Integer> values) {
            addCriterion("avePressure not in", values, "avepressure");
            return (Criteria) this;
        }

        public Criteria andAvepressureBetween(Integer value1, Integer value2) {
            addCriterion("avePressure between", value1, value2, "avepressure");
            return (Criteria) this;
        }

        public Criteria andAvepressureNotBetween(Integer value1, Integer value2) {
            addCriterion("avePressure not between", value1, value2, "avepressure");
            return (Criteria) this;
        }

        public Criteria andAvewindspeedIsNull() {
            addCriterion("aveWindSpeed is null");
            return (Criteria) this;
        }

        public Criteria andAvewindspeedIsNotNull() {
            addCriterion("aveWindSpeed is not null");
            return (Criteria) this;
        }

        public Criteria andAvewindspeedEqualTo(Integer value) {
            addCriterion("aveWindSpeed =", value, "avewindspeed");
            return (Criteria) this;
        }

        public Criteria andAvewindspeedNotEqualTo(Integer value) {
            addCriterion("aveWindSpeed <>", value, "avewindspeed");
            return (Criteria) this;
        }

        public Criteria andAvewindspeedGreaterThan(Integer value) {
            addCriterion("aveWindSpeed >", value, "avewindspeed");
            return (Criteria) this;
        }

        public Criteria andAvewindspeedGreaterThanOrEqualTo(Integer value) {
            addCriterion("aveWindSpeed >=", value, "avewindspeed");
            return (Criteria) this;
        }

        public Criteria andAvewindspeedLessThan(Integer value) {
            addCriterion("aveWindSpeed <", value, "avewindspeed");
            return (Criteria) this;
        }

        public Criteria andAvewindspeedLessThanOrEqualTo(Integer value) {
            addCriterion("aveWindSpeed <=", value, "avewindspeed");
            return (Criteria) this;
        }

        public Criteria andAvewindspeedIn(List<Integer> values) {
            addCriterion("aveWindSpeed in", values, "avewindspeed");
            return (Criteria) this;
        }

        public Criteria andAvewindspeedNotIn(List<Integer> values) {
            addCriterion("aveWindSpeed not in", values, "avewindspeed");
            return (Criteria) this;
        }

        public Criteria andAvewindspeedBetween(Integer value1, Integer value2) {
            addCriterion("aveWindSpeed between", value1, value2, "avewindspeed");
            return (Criteria) this;
        }

        public Criteria andAvewindspeedNotBetween(Integer value1, Integer value2) {
            addCriterion("aveWindSpeed not between", value1, value2, "avewindspeed");
            return (Criteria) this;
        }

        public Criteria andAvetemperatureIsNull() {
            addCriterion("aveTemperature is null");
            return (Criteria) this;
        }

        public Criteria andAvetemperatureIsNotNull() {
            addCriterion("aveTemperature is not null");
            return (Criteria) this;
        }

        public Criteria andAvetemperatureEqualTo(Integer value) {
            addCriterion("aveTemperature =", value, "avetemperature");
            return (Criteria) this;
        }

        public Criteria andAvetemperatureNotEqualTo(Integer value) {
            addCriterion("aveTemperature <>", value, "avetemperature");
            return (Criteria) this;
        }

        public Criteria andAvetemperatureGreaterThan(Integer value) {
            addCriterion("aveTemperature >", value, "avetemperature");
            return (Criteria) this;
        }

        public Criteria andAvetemperatureGreaterThanOrEqualTo(Integer value) {
            addCriterion("aveTemperature >=", value, "avetemperature");
            return (Criteria) this;
        }

        public Criteria andAvetemperatureLessThan(Integer value) {
            addCriterion("aveTemperature <", value, "avetemperature");
            return (Criteria) this;
        }

        public Criteria andAvetemperatureLessThanOrEqualTo(Integer value) {
            addCriterion("aveTemperature <=", value, "avetemperature");
            return (Criteria) this;
        }

        public Criteria andAvetemperatureIn(List<Integer> values) {
            addCriterion("aveTemperature in", values, "avetemperature");
            return (Criteria) this;
        }

        public Criteria andAvetemperatureNotIn(List<Integer> values) {
            addCriterion("aveTemperature not in", values, "avetemperature");
            return (Criteria) this;
        }

        public Criteria andAvetemperatureBetween(Integer value1, Integer value2) {
            addCriterion("aveTemperature between", value1, value2, "avetemperature");
            return (Criteria) this;
        }

        public Criteria andAvetemperatureNotBetween(Integer value1, Integer value2) {
            addCriterion("aveTemperature not between", value1, value2, "avetemperature");
            return (Criteria) this;
        }

        public Criteria andAvevaporpressureIsNull() {
            addCriterion("aveVaporPressure is null");
            return (Criteria) this;
        }

        public Criteria andAvevaporpressureIsNotNull() {
            addCriterion("aveVaporPressure is not null");
            return (Criteria) this;
        }

        public Criteria andAvevaporpressureEqualTo(Integer value) {
            addCriterion("aveVaporPressure =", value, "avevaporpressure");
            return (Criteria) this;
        }

        public Criteria andAvevaporpressureNotEqualTo(Integer value) {
            addCriterion("aveVaporPressure <>", value, "avevaporpressure");
            return (Criteria) this;
        }

        public Criteria andAvevaporpressureGreaterThan(Integer value) {
            addCriterion("aveVaporPressure >", value, "avevaporpressure");
            return (Criteria) this;
        }

        public Criteria andAvevaporpressureGreaterThanOrEqualTo(Integer value) {
            addCriterion("aveVaporPressure >=", value, "avevaporpressure");
            return (Criteria) this;
        }

        public Criteria andAvevaporpressureLessThan(Integer value) {
            addCriterion("aveVaporPressure <", value, "avevaporpressure");
            return (Criteria) this;
        }

        public Criteria andAvevaporpressureLessThanOrEqualTo(Integer value) {
            addCriterion("aveVaporPressure <=", value, "avevaporpressure");
            return (Criteria) this;
        }

        public Criteria andAvevaporpressureIn(List<Integer> values) {
            addCriterion("aveVaporPressure in", values, "avevaporpressure");
            return (Criteria) this;
        }

        public Criteria andAvevaporpressureNotIn(List<Integer> values) {
            addCriterion("aveVaporPressure not in", values, "avevaporpressure");
            return (Criteria) this;
        }

        public Criteria andAvevaporpressureBetween(Integer value1, Integer value2) {
            addCriterion("aveVaporPressure between", value1, value2, "avevaporpressure");
            return (Criteria) this;
        }

        public Criteria andAvevaporpressureNotBetween(Integer value1, Integer value2) {
            addCriterion("aveVaporPressure not between", value1, value2, "avevaporpressure");
            return (Criteria) this;
        }

        public Criteria andAverelativehumidityIsNull() {
            addCriterion("aveRelativeHumidity is null");
            return (Criteria) this;
        }

        public Criteria andAverelativehumidityIsNotNull() {
            addCriterion("aveRelativeHumidity is not null");
            return (Criteria) this;
        }

        public Criteria andAverelativehumidityEqualTo(Integer value) {
            addCriterion("aveRelativeHumidity =", value, "averelativehumidity");
            return (Criteria) this;
        }

        public Criteria andAverelativehumidityNotEqualTo(Integer value) {
            addCriterion("aveRelativeHumidity <>", value, "averelativehumidity");
            return (Criteria) this;
        }

        public Criteria andAverelativehumidityGreaterThan(Integer value) {
            addCriterion("aveRelativeHumidity >", value, "averelativehumidity");
            return (Criteria) this;
        }

        public Criteria andAverelativehumidityGreaterThanOrEqualTo(Integer value) {
            addCriterion("aveRelativeHumidity >=", value, "averelativehumidity");
            return (Criteria) this;
        }

        public Criteria andAverelativehumidityLessThan(Integer value) {
            addCriterion("aveRelativeHumidity <", value, "averelativehumidity");
            return (Criteria) this;
        }

        public Criteria andAverelativehumidityLessThanOrEqualTo(Integer value) {
            addCriterion("aveRelativeHumidity <=", value, "averelativehumidity");
            return (Criteria) this;
        }

        public Criteria andAverelativehumidityIn(List<Integer> values) {
            addCriterion("aveRelativeHumidity in", values, "averelativehumidity");
            return (Criteria) this;
        }

        public Criteria andAverelativehumidityNotIn(List<Integer> values) {
            addCriterion("aveRelativeHumidity not in", values, "averelativehumidity");
            return (Criteria) this;
        }

        public Criteria andAverelativehumidityBetween(Integer value1, Integer value2) {
            addCriterion("aveRelativeHumidity between", value1, value2, "averelativehumidity");
            return (Criteria) this;
        }

        public Criteria andAverelativehumidityNotBetween(Integer value1, Integer value2) {
            addCriterion("aveRelativeHumidity not between", value1, value2, "averelativehumidity");
            return (Criteria) this;
        }

        public Criteria andSunshinetimeIsNull() {
            addCriterion("sunshineTime is null");
            return (Criteria) this;
        }

        public Criteria andSunshinetimeIsNotNull() {
            addCriterion("sunshineTime is not null");
            return (Criteria) this;
        }

        public Criteria andSunshinetimeEqualTo(Integer value) {
            addCriterion("sunshineTime =", value, "sunshinetime");
            return (Criteria) this;
        }

        public Criteria andSunshinetimeNotEqualTo(Integer value) {
            addCriterion("sunshineTime <>", value, "sunshinetime");
            return (Criteria) this;
        }

        public Criteria andSunshinetimeGreaterThan(Integer value) {
            addCriterion("sunshineTime >", value, "sunshinetime");
            return (Criteria) this;
        }

        public Criteria andSunshinetimeGreaterThanOrEqualTo(Integer value) {
            addCriterion("sunshineTime >=", value, "sunshinetime");
            return (Criteria) this;
        }

        public Criteria andSunshinetimeLessThan(Integer value) {
            addCriterion("sunshineTime <", value, "sunshinetime");
            return (Criteria) this;
        }

        public Criteria andSunshinetimeLessThanOrEqualTo(Integer value) {
            addCriterion("sunshineTime <=", value, "sunshinetime");
            return (Criteria) this;
        }

        public Criteria andSunshinetimeIn(List<Integer> values) {
            addCriterion("sunshineTime in", values, "sunshinetime");
            return (Criteria) this;
        }

        public Criteria andSunshinetimeNotIn(List<Integer> values) {
            addCriterion("sunshineTime not in", values, "sunshinetime");
            return (Criteria) this;
        }

        public Criteria andSunshinetimeBetween(Integer value1, Integer value2) {
            addCriterion("sunshineTime between", value1, value2, "sunshinetime");
            return (Criteria) this;
        }

        public Criteria andSunshinetimeNotBetween(Integer value1, Integer value2) {
            addCriterion("sunshineTime not between", value1, value2, "sunshinetime");
            return (Criteria) this;
        }

        public Criteria andDailyminpressyreIsNull() {
            addCriterion("dailyMinPressyre is null");
            return (Criteria) this;
        }

        public Criteria andDailyminpressyreIsNotNull() {
            addCriterion("dailyMinPressyre is not null");
            return (Criteria) this;
        }

        public Criteria andDailyminpressyreEqualTo(Integer value) {
            addCriterion("dailyMinPressyre =", value, "dailyminpressyre");
            return (Criteria) this;
        }

        public Criteria andDailyminpressyreNotEqualTo(Integer value) {
            addCriterion("dailyMinPressyre <>", value, "dailyminpressyre");
            return (Criteria) this;
        }

        public Criteria andDailyminpressyreGreaterThan(Integer value) {
            addCriterion("dailyMinPressyre >", value, "dailyminpressyre");
            return (Criteria) this;
        }

        public Criteria andDailyminpressyreGreaterThanOrEqualTo(Integer value) {
            addCriterion("dailyMinPressyre >=", value, "dailyminpressyre");
            return (Criteria) this;
        }

        public Criteria andDailyminpressyreLessThan(Integer value) {
            addCriterion("dailyMinPressyre <", value, "dailyminpressyre");
            return (Criteria) this;
        }

        public Criteria andDailyminpressyreLessThanOrEqualTo(Integer value) {
            addCriterion("dailyMinPressyre <=", value, "dailyminpressyre");
            return (Criteria) this;
        }

        public Criteria andDailyminpressyreIn(List<Integer> values) {
            addCriterion("dailyMinPressyre in", values, "dailyminpressyre");
            return (Criteria) this;
        }

        public Criteria andDailyminpressyreNotIn(List<Integer> values) {
            addCriterion("dailyMinPressyre not in", values, "dailyminpressyre");
            return (Criteria) this;
        }

        public Criteria andDailyminpressyreBetween(Integer value1, Integer value2) {
            addCriterion("dailyMinPressyre between", value1, value2, "dailyminpressyre");
            return (Criteria) this;
        }

        public Criteria andDailyminpressyreNotBetween(Integer value1, Integer value2) {
            addCriterion("dailyMinPressyre not between", value1, value2, "dailyminpressyre");
            return (Criteria) this;
        }

        public Criteria andDailymintemperatureIsNull() {
            addCriterion("dailyMinTemperature is null");
            return (Criteria) this;
        }

        public Criteria andDailymintemperatureIsNotNull() {
            addCriterion("dailyMinTemperature is not null");
            return (Criteria) this;
        }

        public Criteria andDailymintemperatureEqualTo(Integer value) {
            addCriterion("dailyMinTemperature =", value, "dailymintemperature");
            return (Criteria) this;
        }

        public Criteria andDailymintemperatureNotEqualTo(Integer value) {
            addCriterion("dailyMinTemperature <>", value, "dailymintemperature");
            return (Criteria) this;
        }

        public Criteria andDailymintemperatureGreaterThan(Integer value) {
            addCriterion("dailyMinTemperature >", value, "dailymintemperature");
            return (Criteria) this;
        }

        public Criteria andDailymintemperatureGreaterThanOrEqualTo(Integer value) {
            addCriterion("dailyMinTemperature >=", value, "dailymintemperature");
            return (Criteria) this;
        }

        public Criteria andDailymintemperatureLessThan(Integer value) {
            addCriterion("dailyMinTemperature <", value, "dailymintemperature");
            return (Criteria) this;
        }

        public Criteria andDailymintemperatureLessThanOrEqualTo(Integer value) {
            addCriterion("dailyMinTemperature <=", value, "dailymintemperature");
            return (Criteria) this;
        }

        public Criteria andDailymintemperatureIn(List<Integer> values) {
            addCriterion("dailyMinTemperature in", values, "dailymintemperature");
            return (Criteria) this;
        }

        public Criteria andDailymintemperatureNotIn(List<Integer> values) {
            addCriterion("dailyMinTemperature not in", values, "dailymintemperature");
            return (Criteria) this;
        }

        public Criteria andDailymintemperatureBetween(Integer value1, Integer value2) {
            addCriterion("dailyMinTemperature between", value1, value2, "dailymintemperature");
            return (Criteria) this;
        }

        public Criteria andDailymintemperatureNotBetween(Integer value1, Integer value2) {
            addCriterion("dailyMinTemperature not between", value1, value2, "dailymintemperature");
            return (Criteria) this;
        }

        public Criteria andDailymaxpressyreIsNull() {
            addCriterion("dailyMaxPressyre is null");
            return (Criteria) this;
        }

        public Criteria andDailymaxpressyreIsNotNull() {
            addCriterion("dailyMaxPressyre is not null");
            return (Criteria) this;
        }

        public Criteria andDailymaxpressyreEqualTo(Integer value) {
            addCriterion("dailyMaxPressyre =", value, "dailymaxpressyre");
            return (Criteria) this;
        }

        public Criteria andDailymaxpressyreNotEqualTo(Integer value) {
            addCriterion("dailyMaxPressyre <>", value, "dailymaxpressyre");
            return (Criteria) this;
        }

        public Criteria andDailymaxpressyreGreaterThan(Integer value) {
            addCriterion("dailyMaxPressyre >", value, "dailymaxpressyre");
            return (Criteria) this;
        }

        public Criteria andDailymaxpressyreGreaterThanOrEqualTo(Integer value) {
            addCriterion("dailyMaxPressyre >=", value, "dailymaxpressyre");
            return (Criteria) this;
        }

        public Criteria andDailymaxpressyreLessThan(Integer value) {
            addCriterion("dailyMaxPressyre <", value, "dailymaxpressyre");
            return (Criteria) this;
        }

        public Criteria andDailymaxpressyreLessThanOrEqualTo(Integer value) {
            addCriterion("dailyMaxPressyre <=", value, "dailymaxpressyre");
            return (Criteria) this;
        }

        public Criteria andDailymaxpressyreIn(List<Integer> values) {
            addCriterion("dailyMaxPressyre in", values, "dailymaxpressyre");
            return (Criteria) this;
        }

        public Criteria andDailymaxpressyreNotIn(List<Integer> values) {
            addCriterion("dailyMaxPressyre not in", values, "dailymaxpressyre");
            return (Criteria) this;
        }

        public Criteria andDailymaxpressyreBetween(Integer value1, Integer value2) {
            addCriterion("dailyMaxPressyre between", value1, value2, "dailymaxpressyre");
            return (Criteria) this;
        }

        public Criteria andDailymaxpressyreNotBetween(Integer value1, Integer value2) {
            addCriterion("dailyMaxPressyre not between", value1, value2, "dailymaxpressyre");
            return (Criteria) this;
        }

        public Criteria andDailymaxtemperatureIsNull() {
            addCriterion("dailyMaxTemperature is null");
            return (Criteria) this;
        }

        public Criteria andDailymaxtemperatureIsNotNull() {
            addCriterion("dailyMaxTemperature is not null");
            return (Criteria) this;
        }

        public Criteria andDailymaxtemperatureEqualTo(Integer value) {
            addCriterion("dailyMaxTemperature =", value, "dailymaxtemperature");
            return (Criteria) this;
        }

        public Criteria andDailymaxtemperatureNotEqualTo(Integer value) {
            addCriterion("dailyMaxTemperature <>", value, "dailymaxtemperature");
            return (Criteria) this;
        }

        public Criteria andDailymaxtemperatureGreaterThan(Integer value) {
            addCriterion("dailyMaxTemperature >", value, "dailymaxtemperature");
            return (Criteria) this;
        }

        public Criteria andDailymaxtemperatureGreaterThanOrEqualTo(Integer value) {
            addCriterion("dailyMaxTemperature >=", value, "dailymaxtemperature");
            return (Criteria) this;
        }

        public Criteria andDailymaxtemperatureLessThan(Integer value) {
            addCriterion("dailyMaxTemperature <", value, "dailymaxtemperature");
            return (Criteria) this;
        }

        public Criteria andDailymaxtemperatureLessThanOrEqualTo(Integer value) {
            addCriterion("dailyMaxTemperature <=", value, "dailymaxtemperature");
            return (Criteria) this;
        }

        public Criteria andDailymaxtemperatureIn(List<Integer> values) {
            addCriterion("dailyMaxTemperature in", values, "dailymaxtemperature");
            return (Criteria) this;
        }

        public Criteria andDailymaxtemperatureNotIn(List<Integer> values) {
            addCriterion("dailyMaxTemperature not in", values, "dailymaxtemperature");
            return (Criteria) this;
        }

        public Criteria andDailymaxtemperatureBetween(Integer value1, Integer value2) {
            addCriterion("dailyMaxTemperature between", value1, value2, "dailymaxtemperature");
            return (Criteria) this;
        }

        public Criteria andDailymaxtemperatureNotBetween(Integer value1, Integer value2) {
            addCriterion("dailyMaxTemperature not between", value1, value2, "dailymaxtemperature");
            return (Criteria) this;
        }

        public Criteria andMaxwindspeedIsNull() {
            addCriterion("maxWindSpeed is null");
            return (Criteria) this;
        }

        public Criteria andMaxwindspeedIsNotNull() {
            addCriterion("maxWindSpeed is not null");
            return (Criteria) this;
        }

        public Criteria andMaxwindspeedEqualTo(Integer value) {
            addCriterion("maxWindSpeed =", value, "maxwindspeed");
            return (Criteria) this;
        }

        public Criteria andMaxwindspeedNotEqualTo(Integer value) {
            addCriterion("maxWindSpeed <>", value, "maxwindspeed");
            return (Criteria) this;
        }

        public Criteria andMaxwindspeedGreaterThan(Integer value) {
            addCriterion("maxWindSpeed >", value, "maxwindspeed");
            return (Criteria) this;
        }

        public Criteria andMaxwindspeedGreaterThanOrEqualTo(Integer value) {
            addCriterion("maxWindSpeed >=", value, "maxwindspeed");
            return (Criteria) this;
        }

        public Criteria andMaxwindspeedLessThan(Integer value) {
            addCriterion("maxWindSpeed <", value, "maxwindspeed");
            return (Criteria) this;
        }

        public Criteria andMaxwindspeedLessThanOrEqualTo(Integer value) {
            addCriterion("maxWindSpeed <=", value, "maxwindspeed");
            return (Criteria) this;
        }

        public Criteria andMaxwindspeedIn(List<Integer> values) {
            addCriterion("maxWindSpeed in", values, "maxwindspeed");
            return (Criteria) this;
        }

        public Criteria andMaxwindspeedNotIn(List<Integer> values) {
            addCriterion("maxWindSpeed not in", values, "maxwindspeed");
            return (Criteria) this;
        }

        public Criteria andMaxwindspeedBetween(Integer value1, Integer value2) {
            addCriterion("maxWindSpeed between", value1, value2, "maxwindspeed");
            return (Criteria) this;
        }

        public Criteria andMaxwindspeedNotBetween(Integer value1, Integer value2) {
            addCriterion("maxWindSpeed not between", value1, value2, "maxwindspeed");
            return (Criteria) this;
        }

        public Criteria andDirectionmaxwindspeedIsNull() {
            addCriterion("directionMaxWindSpeed is null");
            return (Criteria) this;
        }

        public Criteria andDirectionmaxwindspeedIsNotNull() {
            addCriterion("directionMaxWindSpeed is not null");
            return (Criteria) this;
        }

        public Criteria andDirectionmaxwindspeedEqualTo(Integer value) {
            addCriterion("directionMaxWindSpeed =", value, "directionmaxwindspeed");
            return (Criteria) this;
        }

        public Criteria andDirectionmaxwindspeedNotEqualTo(Integer value) {
            addCriterion("directionMaxWindSpeed <>", value, "directionmaxwindspeed");
            return (Criteria) this;
        }

        public Criteria andDirectionmaxwindspeedGreaterThan(Integer value) {
            addCriterion("directionMaxWindSpeed >", value, "directionmaxwindspeed");
            return (Criteria) this;
        }

        public Criteria andDirectionmaxwindspeedGreaterThanOrEqualTo(Integer value) {
            addCriterion("directionMaxWindSpeed >=", value, "directionmaxwindspeed");
            return (Criteria) this;
        }

        public Criteria andDirectionmaxwindspeedLessThan(Integer value) {
            addCriterion("directionMaxWindSpeed <", value, "directionmaxwindspeed");
            return (Criteria) this;
        }

        public Criteria andDirectionmaxwindspeedLessThanOrEqualTo(Integer value) {
            addCriterion("directionMaxWindSpeed <=", value, "directionmaxwindspeed");
            return (Criteria) this;
        }

        public Criteria andDirectionmaxwindspeedIn(List<Integer> values) {
            addCriterion("directionMaxWindSpeed in", values, "directionmaxwindspeed");
            return (Criteria) this;
        }

        public Criteria andDirectionmaxwindspeedNotIn(List<Integer> values) {
            addCriterion("directionMaxWindSpeed not in", values, "directionmaxwindspeed");
            return (Criteria) this;
        }

        public Criteria andDirectionmaxwindspeedBetween(Integer value1, Integer value2) {
            addCriterion("directionMaxWindSpeed between", value1, value2, "directionmaxwindspeed");
            return (Criteria) this;
        }

        public Criteria andDirectionmaxwindspeedNotBetween(Integer value1, Integer value2) {
            addCriterion("directionMaxWindSpeed not between", value1, value2, "directionmaxwindspeed");
            return (Criteria) this;
        }

        public Criteria andMinrelativehumidityIsNull() {
            addCriterion("minRelativeHumidity is null");
            return (Criteria) this;
        }

        public Criteria andMinrelativehumidityIsNotNull() {
            addCriterion("minRelativeHumidity is not null");
            return (Criteria) this;
        }

        public Criteria andMinrelativehumidityEqualTo(Integer value) {
            addCriterion("minRelativeHumidity =", value, "minrelativehumidity");
            return (Criteria) this;
        }

        public Criteria andMinrelativehumidityNotEqualTo(Integer value) {
            addCriterion("minRelativeHumidity <>", value, "minrelativehumidity");
            return (Criteria) this;
        }

        public Criteria andMinrelativehumidityGreaterThan(Integer value) {
            addCriterion("minRelativeHumidity >", value, "minrelativehumidity");
            return (Criteria) this;
        }

        public Criteria andMinrelativehumidityGreaterThanOrEqualTo(Integer value) {
            addCriterion("minRelativeHumidity >=", value, "minrelativehumidity");
            return (Criteria) this;
        }

        public Criteria andMinrelativehumidityLessThan(Integer value) {
            addCriterion("minRelativeHumidity <", value, "minrelativehumidity");
            return (Criteria) this;
        }

        public Criteria andMinrelativehumidityLessThanOrEqualTo(Integer value) {
            addCriterion("minRelativeHumidity <=", value, "minrelativehumidity");
            return (Criteria) this;
        }

        public Criteria andMinrelativehumidityIn(List<Integer> values) {
            addCriterion("minRelativeHumidity in", values, "minrelativehumidity");
            return (Criteria) this;
        }

        public Criteria andMinrelativehumidityNotIn(List<Integer> values) {
            addCriterion("minRelativeHumidity not in", values, "minrelativehumidity");
            return (Criteria) this;
        }

        public Criteria andMinrelativehumidityBetween(Integer value1, Integer value2) {
            addCriterion("minRelativeHumidity between", value1, value2, "minrelativehumidity");
            return (Criteria) this;
        }

        public Criteria andMinrelativehumidityNotBetween(Integer value1, Integer value2) {
            addCriterion("minRelativeHumidity not between", value1, value2, "minrelativehumidity");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table weather_data
     *
     * @mbggenerated do_not_delete_during_merge
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table weather_data
     *
     * @mbggenerated
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}