package com.generator.pojo;

public class WeatherDataKey {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column weather_data.numDistricyStation
     *
     * @mbggenerated
     */
    private Integer numdistricystation;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column weather_data.weatherYear
     *
     * @mbggenerated
     */
    private Integer weatheryear;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column weather_data.weatherMonth
     *
     * @mbggenerated
     */
    private Integer weathermonth;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column weather_data.weatherDay
     *
     * @mbggenerated
     */
    private Integer weatherday;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column weather_data.numDistricyStation
     *
     * @return the value of weather_data.numDistricyStation
     *
     * @mbggenerated
     */
    public Integer getNumdistricystation() {
        return numdistricystation;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column weather_data.numDistricyStation
     *
     * @param numdistricystation the value for weather_data.numDistricyStation
     *
     * @mbggenerated
     */
    public void setNumdistricystation(Integer numdistricystation) {
        this.numdistricystation = numdistricystation;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column weather_data.weatherYear
     *
     * @return the value of weather_data.weatherYear
     *
     * @mbggenerated
     */
    public Integer getWeatheryear() {
        return weatheryear;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column weather_data.weatherYear
     *
     * @param weatheryear the value for weather_data.weatherYear
     *
     * @mbggenerated
     */
    public void setWeatheryear(Integer weatheryear) {
        this.weatheryear = weatheryear;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column weather_data.weatherMonth
     *
     * @return the value of weather_data.weatherMonth
     *
     * @mbggenerated
     */
    public Integer getWeathermonth() {
        return weathermonth;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column weather_data.weatherMonth
     *
     * @param weathermonth the value for weather_data.weatherMonth
     *
     * @mbggenerated
     */
    public void setWeathermonth(Integer weathermonth) {
        this.weathermonth = weathermonth;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column weather_data.weatherDay
     *
     * @return the value of weather_data.weatherDay
     *
     * @mbggenerated
     */
    public Integer getWeatherday() {
        return weatherday;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column weather_data.weatherDay
     *
     * @param weatherday the value for weather_data.weatherDay
     *
     * @mbggenerated
     */
    public void setWeatherday(Integer weatherday) {
        this.weatherday = weatherday;
    }
}