package com.zxh.ssm.module.whole.pojo;

public class DiseaseOutbreakKey {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column disease_outbreak.breakYear
     *
     * @mbggenerated
     */
    private Integer breakyear;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column disease_outbreak.breakMonth
     *
     * @mbggenerated
     */
    private Integer breakmonth;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column disease_outbreak.province
     *
     * @mbggenerated
     */
    private String province;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column disease_outbreak.city
     *
     * @mbggenerated
     */
    private String city;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column disease_outbreak.county
     *
     * @mbggenerated
     */
    private String county;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column disease_outbreak.town
     *
     * @mbggenerated
     */
    private String town;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column disease_outbreak.breakYear
     *
     * @return the value of disease_outbreak.breakYear
     *
     * @mbggenerated
     */
    public Integer getBreakyear() {
        return breakyear;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column disease_outbreak.breakYear
     *
     * @param breakyear the value for disease_outbreak.breakYear
     *
     * @mbggenerated
     */
    public void setBreakyear(Integer breakyear) {
        this.breakyear = breakyear;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column disease_outbreak.breakMonth
     *
     * @return the value of disease_outbreak.breakMonth
     *
     * @mbggenerated
     */
    public Integer getBreakmonth() {
        return breakmonth;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column disease_outbreak.breakMonth
     *
     * @param breakmonth the value for disease_outbreak.breakMonth
     *
     * @mbggenerated
     */
    public void setBreakmonth(Integer breakmonth) {
        this.breakmonth = breakmonth;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column disease_outbreak.province
     *
     * @return the value of disease_outbreak.province
     *
     * @mbggenerated
     */
    public String getProvince() {
        return province;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column disease_outbreak.province
     *
     * @param province the value for disease_outbreak.province
     *
     * @mbggenerated
     */
    public void setProvince(String province) {
        this.province = province == null ? null : province.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column disease_outbreak.city
     *
     * @return the value of disease_outbreak.city
     *
     * @mbggenerated
     */
    public String getCity() {
        return city;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column disease_outbreak.city
     *
     * @param city the value for disease_outbreak.city
     *
     * @mbggenerated
     */
    public void setCity(String city) {
        this.city = city == null ? null : city.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column disease_outbreak.county
     *
     * @return the value of disease_outbreak.county
     *
     * @mbggenerated
     */
    public String getCounty() {
        return county;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column disease_outbreak.county
     *
     * @param county the value for disease_outbreak.county
     *
     * @mbggenerated
     */
    public void setCounty(String county) {
        this.county = county == null ? null : county.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column disease_outbreak.town
     *
     * @return the value of disease_outbreak.town
     *
     * @mbggenerated
     */
    public String getTown() {
        return town;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column disease_outbreak.town
     *
     * @param town the value for disease_outbreak.town
     *
     * @mbggenerated
     */
    public void setTown(String town) {
        this.town = town == null ? null : town.trim();
    }
}