package com.zxh.ssm.module.whole.pojo;

import java.util.Date;

public class PatientCasesInformation extends PatientCasesInformationKey {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column patient_cases_information.caseCategory1
     *
     * @mbggenerated
     */
    private String casecategory1;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column patient_cases_information.caseCategory2
     *
     * @mbggenerated
     */
    private String casecategory2;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column patient_cases_information.illDate
     *
     * @mbggenerated
     */
    private Date illdate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column patient_cases_information.confirmDate
     *
     * @mbggenerated
     */
    private String confirmdate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column patient_cases_information.deathDate
     *
     * @mbggenerated
     */
    private String deathdate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column patient_cases_information.diseaseName
     *
     * @mbggenerated
     */
    private String diseasename;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column patient_cases_information.fillCardDoc
     *
     * @mbggenerated
     */
    private String fillcarddoc;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column patient_cases_information.fillCardDate
     *
     * @mbggenerated
     */
    private Date fillcarddate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column patient_cases_information.notes
     *
     * @mbggenerated
     */
    private String notes;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column patient_cases_information.caseCategory1
     *
     * @return the value of patient_cases_information.caseCategory1
     *
     * @mbggenerated
     */
    public String getCasecategory1() {
        return casecategory1;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column patient_cases_information.caseCategory1
     *
     * @param casecategory1 the value for patient_cases_information.caseCategory1
     *
     * @mbggenerated
     */
    public void setCasecategory1(String casecategory1) {
        this.casecategory1 = casecategory1 == null ? null : casecategory1.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column patient_cases_information.caseCategory2
     *
     * @return the value of patient_cases_information.caseCategory2
     *
     * @mbggenerated
     */
    public String getCasecategory2() {
        return casecategory2;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column patient_cases_information.caseCategory2
     *
     * @param casecategory2 the value for patient_cases_information.caseCategory2
     *
     * @mbggenerated
     */
    public void setCasecategory2(String casecategory2) {
        this.casecategory2 = casecategory2 == null ? null : casecategory2.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column patient_cases_information.illDate
     *
     * @return the value of patient_cases_information.illDate
     *
     * @mbggenerated
     */
    public Date getIlldate() {
        return illdate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column patient_cases_information.illDate
     *
     * @param illdate the value for patient_cases_information.illDate
     *
     * @mbggenerated
     */
    public void setIlldate(Date illdate) {
        this.illdate = illdate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column patient_cases_information.confirmDate
     *
     * @return the value of patient_cases_information.confirmDate
     *
     * @mbggenerated
     */
    public String getConfirmdate() {
        return confirmdate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column patient_cases_information.confirmDate
     *
     * @param confirmdate the value for patient_cases_information.confirmDate
     *
     * @mbggenerated
     */
    public void setConfirmdate(String confirmdate) {
        this.confirmdate = confirmdate == null ? null : confirmdate.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column patient_cases_information.deathDate
     *
     * @return the value of patient_cases_information.deathDate
     *
     * @mbggenerated
     */
    public String getDeathdate() {
        return deathdate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column patient_cases_information.deathDate
     *
     * @param deathdate the value for patient_cases_information.deathDate
     *
     * @mbggenerated
     */
    public void setDeathdate(String deathdate) {
        this.deathdate = deathdate == null ? null : deathdate.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column patient_cases_information.diseaseName
     *
     * @return the value of patient_cases_information.diseaseName
     *
     * @mbggenerated
     */
    public String getDiseasename() {
        return diseasename;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column patient_cases_information.diseaseName
     *
     * @param diseasename the value for patient_cases_information.diseaseName
     *
     * @mbggenerated
     */
    public void setDiseasename(String diseasename) {
        this.diseasename = diseasename == null ? null : diseasename.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column patient_cases_information.fillCardDoc
     *
     * @return the value of patient_cases_information.fillCardDoc
     *
     * @mbggenerated
     */
    public String getFillcarddoc() {
        return fillcarddoc;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column patient_cases_information.fillCardDoc
     *
     * @param fillcarddoc the value for patient_cases_information.fillCardDoc
     *
     * @mbggenerated
     */
    public void setFillcarddoc(String fillcarddoc) {
        this.fillcarddoc = fillcarddoc == null ? null : fillcarddoc.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column patient_cases_information.fillCardDate
     *
     * @return the value of patient_cases_information.fillCardDate
     *
     * @mbggenerated
     */
    public Date getFillcarddate() {
        return fillcarddate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column patient_cases_information.fillCardDate
     *
     * @param fillcarddate the value for patient_cases_information.fillCardDate
     *
     * @mbggenerated
     */
    public void setFillcarddate(Date fillcarddate) {
        this.fillcarddate = fillcarddate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column patient_cases_information.notes
     *
     * @return the value of patient_cases_information.notes
     *
     * @mbggenerated
     */
    public String getNotes() {
        return notes;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column patient_cases_information.notes
     *
     * @param notes the value for patient_cases_information.notes
     *
     * @mbggenerated
     */
    public void setNotes(String notes) {
        this.notes = notes == null ? null : notes.trim();
    }
}