package com.zxh.ssm.module.whole.pojo;

public class PatientCasesInformationKey {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column patient_cases_information.year
     *
     * @mbggenerated
     */
    private Integer year;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column patient_cases_information.cardID
     *
     * @mbggenerated
     */
    private Integer cardid;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column patient_cases_information.year
     *
     * @return the value of patient_cases_information.year
     *
     * @mbggenerated
     */
    public Integer getYear() {
        return year;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column patient_cases_information.year
     *
     * @param year the value for patient_cases_information.year
     *
     * @mbggenerated
     */
    public void setYear(Integer year) {
        this.year = year;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column patient_cases_information.cardID
     *
     * @return the value of patient_cases_information.cardID
     *
     * @mbggenerated
     */
    public Integer getCardid() {
        return cardid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column patient_cases_information.cardID
     *
     * @param cardid the value for patient_cases_information.cardID
     *
     * @mbggenerated
     */
    public void setCardid(Integer cardid) {
        this.cardid = cardid;
    }
}